// Generated by scripts/generate-model-types.py from bindings/obby-wasm/src/types.d.ts.
// Do not edit by hand.
//
// Field names mirror the wire's snake_case rather than being recased to lowerCamelCase, so
// this file keeps its own naming and null-check style rather than the package's.
// ignore_for_file: non_constant_identifier_names, constant_identifier_names
// ignore_for_file: prefer_if_null_operators, prefer_null_aware_operators
library;

/// The set of commands the server says we may currently use.
/// The server pushes this on connect and again whenever it changes, such as after an `OPER`. A
/// batch carries additions and removals together, so both are applied at once.
class AllowedCommands {
  const AllowedCommands({
    required this.available,
  });

  factory AllowedCommands.fromJson(Map<String, dynamic> json) => AllowedCommands(
    available: (json['available'] as List).map((e) => e as String).toList(),
  );

  Map<String, dynamic> toJson() => {
    'available': available.map((e) => e).toList(),
  };

  final List<String> available;
}

/// What the server knows about a bot in a channel.
class Bot {
  const Bot({
    required this.nick,
    required this.id,
    required this.from_config,
    required this.commands,
  });

  factory Bot.fromJson(Map<String, dynamic> json) => Bot(
    nick: json['nick'] as String,
    id: json['id'] == null ? null : json['id'] as String,
    from_config: json['from_config'] as bool,
    commands: (json['commands'] as List).map((e) => BotCommand.fromJson(e as Map<String, dynamic>)).toList(),
  );

  Map<String, dynamic> toJson() => {
    'nick': nick,
    'id': id,
    'from_config': from_config,
    'commands': commands.map((e) => e.toJson()).toList(),
  };

  /// The bot's nick.
  final String nick;

  /// The identifier the server gave it.
  final String? id;

  /// True when an operator configured this bot, rather than it registering itself.
  /// Only a configured bot may claim a privileged command name. A bot that registered itself has
  /// those names stripped, so it cannot shadow `oper` or `identify`.
  final bool from_config;

  /// The commands it offers.
  final List<BotCommand> commands;
}

/// One command a bot offers.
class BotCommand {
  const BotCommand({
    required this.name,
    required this.description,
  });

  factory BotCommand.fromJson(Map<String, dynamic> json) => BotCommand(
    name: json['name'] as String,
    description: json['description'] == null ? null : json['description'] as String,
  );

  Map<String, dynamic> toJson() => {
    'name': name,
    'description': description,
  };

  /// What to type, without its leading slash.
  final String name;

  /// What it does.
  final String? description;
}

/// The bots we know about, keyed by their folded nick.
class BotRegistry {
  const BotRegistry({
    required this.known,
  });

  factory BotRegistry.fromJson(Map<String, dynamic> json) => BotRegistry(
    known: (json['known'] as Map<String, dynamic>).map((k, v) => MapEntry(k, Bot.fromJson(v as Map<String, dynamic>))),
  );

  Map<String, dynamic> toJson() => {
    'known': known.map((k, v) => MapEntry(k, v.toJson())),
  };

  final Map<String, Bot> known;
}

/// What the server offers and what we hold.
class Capabilities {
  const Capabilities({
    required this.available,
    required this.acknowledged,
    required this.pending,
  });

  factory Capabilities.fromJson(Map<String, dynamic> json) => Capabilities(
    available: (json['available'] as Map<String, dynamic>).map((k, v) => MapEntry(k, v == null ? null : v as String)),
    acknowledged: (json['acknowledged'] as Map<String, dynamic>).map((k, v) => MapEntry(k, v == null ? null : v as String)),
    pending: (json['pending'] as List).map((e) => e as String).toList(),
  );

  Map<String, dynamic> toJson() => {
    'available': available.map((k, v) => MapEntry(k, v)),
    'acknowledged': acknowledged.map((k, v) => MapEntry(k, v)),
    'pending': pending.map((e) => e).toList(),
  };

  final Map<String, String?> available;

  final Map<String, String?> acknowledged;

  /// Capabilities we asked for and are still waiting on. Registration cannot finish while this is
  /// non-empty, because `CAP END` before the last reply loses the capability.
  final List<String> pending;
}

/// One capability the server advertised, with the value it carried if any.
class Capability {
  const Capability({
    required this.name,
    required this.value,
  });

  factory Capability.fromJson(Map<String, dynamic> json) => Capability(
    name: json['name'] as String,
    value: json['value'] == null ? null : json['value'] as String,
  );

  Map<String, dynamic> toJson() => {
    'name': name,
    'value': value,
  };

  /// The capability name, without any `=value` suffix.
  final String name;

  /// The value, for capabilities like `sasl=PLAIN,EXTERNAL` that carry one.
  final String? value;
}

/// A nick or channel name folded under a server's casemapping.
/// Every map keyed by a nick or a channel is keyed by this type, so that a raw `String` can never be
/// used as an identity by accident.
/// The mapping that produced it is not stored. Two `CaseFolded` values are only comparable when they
/// came from the same connection, which is the only place they are ever used together.
typedef CaseFolded = String;

/// A channel we are in.
class Channel {
  const Channel({
    required this.name,
    required this.topic,
    required this.topic_by,
    required this.modes,
    required this.members,
    required this.log,
    required this.unread,
    required this.mentions,
    required this.metadata,
    required this.read_marker,
    required this.typing,
    required this.named_modes,
  });

  factory Channel.fromJson(Map<String, dynamic> json) => Channel(
    name: json['name'] as String,
    topic: json['topic'] == null ? null : json['topic'] as String,
    topic_by: json['topic_by'] == null ? null : json['topic_by'] as String,
    modes: (json['modes'] as Map<String, dynamic>).map((k, v) => MapEntry(k, v == null ? null : v as String)),
    members: (json['members'] as Map<String, dynamic>).map((k, v) => MapEntry(k, Membership.fromJson(v as Map<String, dynamic>))),
    log: MessageLog.fromJson(json['log'] as Map<String, dynamic>),
    unread: json['unread'] as int,
    mentions: json['mentions'] as int,
    metadata: (json['metadata'] as Map<String, dynamic>).map((k, v) => MapEntry(k, v as String)),
    read_marker: json['read_marker'] == null ? null : json['read_marker'] as String,
    typing: (json['typing'] as List).map((e) => e as CaseFolded).toList(),
    named_modes: (json['named_modes'] as Map<String, dynamic>).map((k, v) => MapEntry(k, v == null ? null : v as String)),
  );

  Map<String, dynamic> toJson() => {
    'name': name,
    'topic': topic,
    'topic_by': topic_by,
    'modes': modes.map((k, v) => MapEntry(k, v)),
    'members': members.map((k, v) => MapEntry(k, v.toJson())),
    'log': log.toJson(),
    'unread': unread,
    'mentions': mentions,
    'metadata': metadata.map((k, v) => MapEntry(k, v)),
    'read_marker': read_marker,
    'typing': typing.map((e) => e).toList(),
    'named_modes': named_modes.map((k, v) => MapEntry(k, v)),
  };

  /// The name as the server spells it.
  final String name;

  /// The topic, when one is set.
  final String? topic;

  /// Who set the topic and when.
  final String? topic_by;

  /// Channel modes currently set, with their arguments.
  final Map<String, String?> modes;

  /// Who is in it.
  final Map<CaseFolded, Membership> members;

  /// What was said.
  final MessageLog log;

  /// Messages since the last read marker.
  final int unread;

  /// Unread messages that mention us.
  final int mentions;

  /// Metadata the server holds, such as `display-name`, `color`, `avatar` and `bot`.
  /// These are plain `draft/metadata-2` keys with no vendor prefix, despite everything else Obby
  /// adds being namespaced.
  final Map<String, String> metadata;

  /// The read marker timestamp the server last confirmed.
  final String? read_marker;

  /// Who is composing a message here right now.
  final List<CaseFolded> typing;

  /// Modes by their name rather than their letter, from `draft/named-modes`.
  /// A letter means nothing without the server telling you what it does, and two servers spell
  /// the same feature differently. The names are stable, so this is what a user interface should
  /// show and what a setting should be keyed by.
  final Map<String, String?> named_modes;
}

/// One message, as the model holds it.
class ChatMessage {
  const ChatMessage({
    required this.key,
    required this.msgid,
    required this.sender,
    required this.kind,
    required this.text,
    required this.account,
    required this.historical,
    required this.own,
    required this.reply_to,
    required this.reactions,
    required this.link_preview,
    required this.redacted,
  });

  factory ChatMessage.fromJson(Map<String, dynamic> json) => ChatMessage(
    key: MessageKey.fromJson(json['key'] as Map<String, dynamic>),
    msgid: json['msgid'] == null ? null : json['msgid'] as String,
    sender: json['sender'] as String,
    kind: MessageKind.fromJson(json['kind'] as Map<String, dynamic>),
    text: json['text'] as String,
    account: json['account'] == null ? null : json['account'] as String,
    historical: json['historical'] as bool,
    own: json['own'] as bool,
    reply_to: json['reply_to'] == null ? null : json['reply_to'] as String,
    reactions: (json['reactions'] as Map<String, dynamic>).map((k, v) => MapEntry(k, (v as List).map((e) => e as String).toList())),
    link_preview: json['link_preview'] == null ? null : LinkPreview.fromJson(json['link_preview'] as Map<String, dynamic>),
    redacted: json['redacted'] as bool,
  );

  Map<String, dynamic> toJson() => {
    'key': key.toJson(),
    'msgid': msgid,
    'sender': sender,
    'kind': kind.toJson(),
    'text': text,
    'account': account,
    'historical': historical,
    'own': own,
    'reply_to': reply_to,
    'reactions': reactions.map((k, v) => MapEntry(k, v.map((e) => e).toList())),
    'link_preview': link_preview?.toJson(),
    'redacted': redacted,
  };

  /// Where it sits in the log.
  final MessageKey key;

  /// The network-unique id, when the server assigned one.
  final String? msgid;

  /// Who sent it, as they spell their own nick.
  final String sender;

  /// What kind of event it is.
  final MessageKind kind;

  /// The body, empty for events that have none.
  final String text;

  /// The account the sender was logged in as, from `account-tag`.
  final String? account;

  /// True when this arrived inside a history batch rather than live.
  final bool historical;

  /// True when this is our own message coming back through `echo-message`.
  final bool own;

  /// The message this one replies to, from the `+reply` tag.
  /// The server is inconsistent about the spelling and sends `+reply` from one module and
  /// `+draft/reply` from another, so both are accepted on the way in.
  final String? reply_to;

  /// Reactions, keyed by the emoji, holding who reacted.
  final Map<String, List<String>> reactions;

  /// A preview of the first link in this message, when the server built one.
  final LinkPreview? link_preview;

  /// True once the message was redacted. The original is kept, because throwing it away leaves no
  /// way to show who redacted what.
  final bool redacted;
}

/// The chunk-correlation fields riding alongside a split `sdp` value.
class ChunkMeta {
  const ChunkMeta({
    required this.id,
    required this.seq,
    required this.total,
  });

  factory ChunkMeta.fromJson(Map<String, dynamic> json) => ChunkMeta(
    id: json['id'] as String,
    seq: json['seq'] as int,
    total: json['total'] as int,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'seq': seq,
    'total': total,
  };

  /// The id every chunk of one split frame shares.
  final String id;

  /// This chunk's 0-based position.
  final int seq;

  /// How many chunks the split frame was cut into.
  final int total;
}

/// Something to do on this connection.
sealed class Command {
  const Command();

  Map<String, dynamic> toJson();

  factory Command.fromJson(Map<String, dynamic> json) {
    final tag = json['type'] as String;
    return switch (tag) {
      'join' => CommandJoin.fromJson(json),
      'part' => CommandPart.fromJson(json),
      'send_message' => CommandSendMessage.fromJson(json),
      'send_notice' => CommandSendNotice.fromJson(json),
      'send_action' => CommandSendAction.fromJson(json),
      'set_nick' => CommandSetNick.fromJson(json),
      'set_topic' => CommandSetTopic.fromJson(json),
      'set_away' => CommandSetAway.fromJson(json),
      'set_typing' => CommandSetTyping.fromJson(json),
      'add_reaction' => CommandAddReaction.fromJson(json),
      'remove_reaction' => CommandRemoveReaction.fromJson(json),
      'redact_message' => CommandRedactMessage.fromJson(json),
      'mark_read' => CommandMarkRead.fromJson(json),
      'fetch_history' => CommandFetchHistory.fromJson(json),
      'set_metadata' => CommandSetMetadata.fromJson(json),
      'subscribe_metadata' => CommandSubscribeMetadata.fromJson(json),
      'whois' => CommandWhois.fromJson(json),
      'rename_channel' => CommandRenameChannel.fromJson(json),
      'create_invite_link' => CommandCreateInviteLink.fromJson(json),
      'list_invite_links' => CommandListInviteLinks.fromJson(json),
      'delete_invite_link' => CommandDeleteInviteLink.fromJson(json),
      'redeem_invite_code' => CommandRedeemInviteCode.fromJson(json),
      'generate_token' => CommandGenerateToken.fromJson(json),
      'watch_nicks' => CommandWatchNicks.fromJson(json),
      'unwatch_nicks' => CommandUnwatchNicks.fromJson(json),
      'send_voice_signal' => CommandSendVoiceSignal.fromJson(json),
      'quit' => CommandQuit.fromJson(json),
      'send_raw_line' => CommandSendRawLine.fromJson(json),
      _ => throw ArgumentError.value(tag, 'type', 'unknown Command variant'),
    };
  }
}

class CommandJoin extends Command {
  const CommandJoin({
    required this.channel,
    required this.key,
  });

  factory CommandJoin.fromJson(Map<String, dynamic> json) => CommandJoin(
    channel: json['channel'] as String,
    key: json['key'] == null ? null : json['key'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'join',
    'channel': channel,
    'key': key,
  };

  /// The channel to join.
  final String channel;

  /// Its key, when it has one.
  final String? key;
}

class CommandPart extends Command {
  const CommandPart({
    required this.channel,
    required this.reason,
  });

  factory CommandPart.fromJson(Map<String, dynamic> json) => CommandPart(
    channel: json['channel'] as String,
    reason: json['reason'] == null ? null : json['reason'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'part',
    'channel': channel,
    'reason': reason,
  };

  /// The channel to leave.
  final String channel;

  /// Why, shown to the others in it.
  final String? reason;
}

class CommandSendMessage extends Command {
  const CommandSendMessage({
    required this.target,
    required this.text,
  });

  factory CommandSendMessage.fromJson(Map<String, dynamic> json) => CommandSendMessage(
    target: json['target'] as String,
    text: json['text'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'send_message',
    'target': target,
    'text': text,
  };

  /// Where to say it.
  final String target;

  /// What to say.
  final String text;
}

class CommandSendNotice extends Command {
  const CommandSendNotice({
    required this.target,
    required this.text,
  });

  factory CommandSendNotice.fromJson(Map<String, dynamic> json) => CommandSendNotice(
    target: json['target'] as String,
    text: json['text'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'send_notice',
    'target': target,
    'text': text,
  };

  /// Where to send it.
  final String target;

  /// What to send.
  final String text;
}

class CommandSendAction extends Command {
  const CommandSendAction({
    required this.target,
    required this.text,
  });

  factory CommandSendAction.fromJson(Map<String, dynamic> json) => CommandSendAction(
    target: json['target'] as String,
    text: json['text'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'send_action',
    'target': target,
    'text': text,
  };

  /// Where to send it.
  final String target;

  /// What we are doing.
  final String text;
}

class CommandSetNick extends Command {
  const CommandSetNick({
    required this.nick,
  });

  factory CommandSetNick.fromJson(Map<String, dynamic> json) => CommandSetNick(
    nick: json['nick'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'set_nick',
    'nick': nick,
  };

  /// The nick to take.
  final String nick;
}

class CommandSetTopic extends Command {
  const CommandSetTopic({
    required this.channel,
    required this.topic,
  });

  factory CommandSetTopic.fromJson(Map<String, dynamic> json) => CommandSetTopic(
    channel: json['channel'] as String,
    topic: json['topic'] == null ? null : json['topic'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'set_topic',
    'channel': channel,
    'topic': topic,
  };

  /// The channel.
  final String channel;

  /// The new topic, or nothing to clear it.
  final String? topic;
}

class CommandSetAway extends Command {
  const CommandSetAway({
    required this.message,
  });

  factory CommandSetAway.fromJson(Map<String, dynamic> json) => CommandSetAway(
    message: json['message'] == null ? null : json['message'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'set_away',
    'message': message,
  };

  /// The away message, or nothing to come back.
  final String? message;
}

class CommandSetTyping extends Command {
  const CommandSetTyping({
    required this.target,
    required this.state,
  });

  factory CommandSetTyping.fromJson(Map<String, dynamic> json) => CommandSetTyping(
    target: json['target'] as String,
    state: TypingState.fromWire(json['state'] as String),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'set_typing',
    'target': target,
    'state': state.wire,
  };

  /// Who we are typing to.
  final String target;

  /// How far along we are.
  final TypingState state;
}

class CommandAddReaction extends Command {
  const CommandAddReaction({
    required this.target,
    required this.msgid,
    required this.emoji,
  });

  factory CommandAddReaction.fromJson(Map<String, dynamic> json) => CommandAddReaction(
    target: json['target'] as String,
    msgid: json['msgid'] as String,
    emoji: json['emoji'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'add_reaction',
    'target': target,
    'msgid': msgid,
    'emoji': emoji,
  };

  /// The channel or person the message is in.
  final String target;

  /// The message reacted to.
  final String msgid;

  /// The emoji.
  final String emoji;
}

class CommandRemoveReaction extends Command {
  const CommandRemoveReaction({
    required this.target,
    required this.msgid,
    required this.emoji,
  });

  factory CommandRemoveReaction.fromJson(Map<String, dynamic> json) => CommandRemoveReaction(
    target: json['target'] as String,
    msgid: json['msgid'] as String,
    emoji: json['emoji'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'remove_reaction',
    'target': target,
    'msgid': msgid,
    'emoji': emoji,
  };

  /// The channel or person the message is in.
  final String target;

  /// The message.
  final String msgid;

  /// The emoji to remove.
  final String emoji;
}

class CommandRedactMessage extends Command {
  const CommandRedactMessage({
    required this.target,
    required this.msgid,
    required this.reason,
  });

  factory CommandRedactMessage.fromJson(Map<String, dynamic> json) => CommandRedactMessage(
    target: json['target'] as String,
    msgid: json['msgid'] as String,
    reason: json['reason'] == null ? null : json['reason'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'redact_message',
    'target': target,
    'msgid': msgid,
    'reason': reason,
  };

  /// Where the message is.
  final String target;

  /// The message to delete.
  final String msgid;

  /// Why, when the server wants a reason.
  final String? reason;
}

class CommandMarkRead extends Command {
  const CommandMarkRead({
    required this.target,
    required this.at_ms,
  });

  factory CommandMarkRead.fromJson(Map<String, dynamic> json) => CommandMarkRead(
    target: json['target'] as String,
    at_ms: json['at_ms'] as int,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'mark_read',
    'target': target,
    'at_ms': at_ms,
  };

  /// The channel or person.
  final String target;

  /// The last message read, in milliseconds since the Unix epoch. The engine writes the
  /// `server-time` the wire wants.
  final int at_ms;
}

class CommandFetchHistory extends Command {
  const CommandFetchHistory({
    required this.target,
    required this.before_msgid,
    required this.limit,
  });

  factory CommandFetchHistory.fromJson(Map<String, dynamic> json) => CommandFetchHistory(
    target: json['target'] as String,
    before_msgid: json['before_msgid'] == null ? null : json['before_msgid'] as String,
    limit: json['limit'] as int,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'fetch_history',
    'target': target,
    'before_msgid': before_msgid,
    'limit': limit,
  };

  /// The channel or person.
  final String target;

  /// Fetch messages older than the message with this id.
  final String? before_msgid;

  /// How many to ask for.
  final int limit;
}

class CommandSetMetadata extends Command {
  const CommandSetMetadata({
    required this.key,
    required this.value,
  });

  factory CommandSetMetadata.fromJson(Map<String, dynamic> json) => CommandSetMetadata(
    key: json['key'] as String,
    value: json['value'] == null ? null : json['value'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'set_metadata',
    'key': key,
    'value': value,
  };

  /// The key, such as `display-name`, `color` or `avatar`.
  final String key;

  /// The value, or nothing to clear the key.
  final String? value;
}

class CommandSubscribeMetadata extends Command {
  const CommandSubscribeMetadata({
    required this.keys,
  });

  factory CommandSubscribeMetadata.fromJson(Map<String, dynamic> json) => CommandSubscribeMetadata(
    keys: (json['keys'] as List).map((e) => e as String).toList(),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'subscribe_metadata',
    'keys': keys.map((e) => e).toList(),
  };

  /// The keys to watch.
  final List<String> keys;
}

class CommandWhois extends Command {
  const CommandWhois({
    required this.nick,
  });

  factory CommandWhois.fromJson(Map<String, dynamic> json) => CommandWhois(
    nick: json['nick'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'whois',
    'nick': nick,
  };

  /// Who to ask about.
  final String nick;
}

class CommandRenameChannel extends Command {
  const CommandRenameChannel({
    required this.channel,
    required this.new_name,
    required this.reason,
  });

  factory CommandRenameChannel.fromJson(Map<String, dynamic> json) => CommandRenameChannel(
    channel: json['channel'] as String,
    new_name: json['new_name'] as String,
    reason: json['reason'] == null ? null : json['reason'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'rename_channel',
    'channel': channel,
    'new_name': new_name,
    'reason': reason,
  };

  /// The channel as it is called now.
  final String channel;

  /// What to call it.
  final String new_name;

  /// Why, shown to the others in it.
  final String? reason;
}

class CommandCreateInviteLink extends Command {
  const CommandCreateInviteLink({
    required this.channel,
    required this.description,
  });

  factory CommandCreateInviteLink.fromJson(Map<String, dynamic> json) => CommandCreateInviteLink(
    channel: json['channel'] == null ? null : json['channel'] as String,
    description: json['description'] == null ? null : json['description'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'create_invite_link',
    'channel': channel,
    'description': description,
  };

  /// The channel it joins, or nothing to invite to the network.
  final String? channel;

  /// What it is for.
  final String? description;
}

class CommandListInviteLinks extends Command {
  const CommandListInviteLinks();

  factory CommandListInviteLinks.fromJson(Map<String, dynamic> json) => const CommandListInviteLinks();

  @override
  Map<String, dynamic> toJson() => {'type': 'list_invite_links'};
}

class CommandDeleteInviteLink extends Command {
  const CommandDeleteInviteLink({
    required this.share_id,
  });

  factory CommandDeleteInviteLink.fromJson(Map<String, dynamic> json) => CommandDeleteInviteLink(
    share_id: json['share_id'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'delete_invite_link',
    'share_id': share_id,
  };

  /// Which one, from [`Command::ListInviteLinks`].
  final String share_id;
}

class CommandRedeemInviteCode extends Command {
  const CommandRedeemInviteCode({
    required this.code,
  });

  factory CommandRedeemInviteCode.fromJson(Map<String, dynamic> json) => CommandRedeemInviteCode(
    code: json['code'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'redeem_invite_code',
    'code': code,
  };

  /// The code, which is the share id of the link that carried it.
  final String code;
}

class CommandGenerateToken extends Command {
  const CommandGenerateToken({
    required this.service,
  });

  factory CommandGenerateToken.fromJson(Map<String, dynamic> json) => CommandGenerateToken(
    service: json['service'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'generate_token',
    'service': service,
  };

  /// Which service the token is for, such as `FILEHOST`.
  final String service;
}

class CommandWatchNicks extends Command {
  const CommandWatchNicks({
    required this.nicks,
  });

  factory CommandWatchNicks.fromJson(Map<String, dynamic> json) => CommandWatchNicks(
    nicks: (json['nicks'] as List).map((e) => e as String).toList(),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'watch_nicks',
    'nicks': nicks.map((e) => e).toList(),
  };

  /// The nicks to watch.
  final List<String> nicks;
}

class CommandUnwatchNicks extends Command {
  const CommandUnwatchNicks({
    required this.nicks,
  });

  factory CommandUnwatchNicks.fromJson(Map<String, dynamic> json) => CommandUnwatchNicks(
    nicks: (json['nicks'] as List).map((e) => e as String).toList(),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'unwatch_nicks',
    'nicks': nicks.map((e) => e).toList(),
  };

  /// The nicks to stop watching.
  final List<String> nicks;
}

class CommandSendVoiceSignal extends Command {
  const CommandSendVoiceSignal({
    required this.channel,
    required this.signal,
  });

  factory CommandSendVoiceSignal.fromJson(Map<String, dynamic> json) => CommandSendVoiceSignal(
    channel: json['channel'] as String,
    signal: VoiceSignal.fromJson(json['signal'] as Map<String, dynamic>),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'send_voice_signal',
    'channel': channel,
    'signal': signal.toJson(),
  };

  /// The channel to signal in.
  final String channel;

  /// The frame. The engine encodes it as the JSON that travels in the tag.
  final VoiceSignal signal;
}

class CommandQuit extends Command {
  const CommandQuit({
    required this.reason,
  });

  factory CommandQuit.fromJson(Map<String, dynamic> json) => CommandQuit(
    reason: json['reason'] == null ? null : json['reason'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'quit',
    'reason': reason,
  };

  /// Why.
  final String? reason;
}

class CommandSendRawLine extends Command {
  const CommandSendRawLine({
    required this.line,
  });

  factory CommandSendRawLine.fromJson(Map<String, dynamic> json) => CommandSendRawLine(
    line: json['line'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'send_raw_line',
    'line': line,
  };

  /// The line, without its terminator.
  final String line;
}

/// What a host needs to give the engine before it can connect.
/// Every field but the nick has a default, so a host deserialising one only has to supply what it
/// actually cares about. An empty username or realname is filled in from the nick.
class Config {
  const Config({
    required this.nick,
    this.username,
    this.realname,
    this.password,
    this.sasl,
    this.retention,
    this.alt_nicks,
  });

  factory Config.fromJson(Map<String, dynamic> json) => Config(
    nick: json['nick'] as String,
    username: json['username'] == null ? null : json['username'] as String,
    realname: json['realname'] == null ? null : json['realname'] as String,
    password: json['password'] == null ? null : json['password'] as String,
    sasl: json['sasl'] == null ? null : SaslCredentials.fromJson(json['sasl'] as Map<String, dynamic>),
    retention: json['retention'] == null ? null : json['retention'] as int,
    alt_nicks: json['alt_nicks'] == null ? null : (json['alt_nicks'] as List).map((e) => e as String).toList(),
  );

  Map<String, dynamic> toJson() => {
    'nick': nick,
    'username': username,
    'realname': realname,
    'password': password,
    'sasl': sasl?.toJson(),
    'retention': retention,
    'alt_nicks': alt_nicks?.map((e) => e).toList(),
  };

  /// The nick to register with.
  final String nick;

  /// The username sent in `USER`. Defaults to the nick.
  final String? username;

  /// The realname sent in `USER`. Defaults to the nick.
  final String? realname;

  /// The server password, sent as `PASS` before anything else.
  final String? password;

  /// What to authenticate with, when the server offers `sasl`.
  final SaslCredentials? sasl;

  /// How many messages each channel and conversation keeps.
  final int? retention;

  /// Nicks to fall back through when the server says ours is taken during registration.
  /// Registration stalls forever if nobody answers a 433, so the engine walks this list and then
  /// starts appending underscores rather than leaving the connection hung.
  final List<String>? alt_nicks;
}

/// How far the connection has got.
enum ConnectionPhase {
  disconnected,
  negotiating,
  registering,
  registered;

  static ConnectionPhase fromWire(String wire) => ConnectionPhase.values.byName(wire);

  String get wire => name;
}

/// A private conversation with one other person.
class Conversation {
  const Conversation({
    required this.nick,
    required this.log,
    required this.unread,
    required this.read_marker,
    required this.typing,
  });

  factory Conversation.fromJson(Map<String, dynamic> json) => Conversation(
    nick: json['nick'] as String,
    log: MessageLog.fromJson(json['log'] as Map<String, dynamic>),
    unread: json['unread'] as int,
    read_marker: json['read_marker'] == null ? null : json['read_marker'] as String,
    typing: (json['typing'] as List).map((e) => e as CaseFolded).toList(),
  );

  Map<String, dynamic> toJson() => {
    'nick': nick,
    'log': log.toJson(),
    'unread': unread,
    'read_marker': read_marker,
    'typing': typing.map((e) => e).toList(),
  };

  /// Their nick, as they spell it.
  final String nick;

  /// What was said.
  final MessageLog log;

  /// Messages since the last read marker.
  final int unread;

  /// The read marker timestamp the server last confirmed.
  final String? read_marker;

  /// Who is composing a message here right now.
  final List<CaseFolded> typing;
}

/// An invitation link to the network or to one channel.
class Invitation {
  const Invitation({
    required this.share_id,
    required this.channel,
    required this.url,
    required this.created,
    required this.redeemed,
    required this.description,
  });

  factory Invitation.fromJson(Map<String, dynamic> json) => Invitation(
    share_id: json['share_id'] as String,
    channel: json['channel'] == null ? null : json['channel'] as String,
    url: json['url'] as String,
    created: json['created'] == null ? null : json['created'] as String,
    redeemed: json['redeemed'] as int,
    description: json['description'] == null ? null : json['description'] as String,
  );

  Map<String, dynamic> toJson() => {
    'share_id': share_id,
    'channel': channel,
    'url': url,
    'created': created,
    'redeemed': redeemed,
    'description': description,
  };

  /// The identifier used to delete it.
  final String share_id;

  /// The channel it joins, or nothing when it invites to the network.
  final String? channel;

  /// The link itself.
  final String url;

  /// When it was made, as the server spells it.
  final String? created;

  /// How many people have used it.
  final int redeemed;

  /// What it is for.
  final String? description;
}

/// A preview of a link someone posted, built by the server and attached to the message.
/// The server fetches the page; a client never does. There is no capability to negotiate, and the
/// server refuses these tags from any sender but itself, so a peer cannot forge one.
class LinkPreview {
  const LinkPreview({
    required this.title,
    required this.snippet,
    required this.image,
  });

  factory LinkPreview.fromJson(Map<String, dynamic> json) => LinkPreview(
    title: json['title'] as String,
    snippet: json['snippet'] == null ? null : json['snippet'] as String,
    image: json['image'] == null ? null : json['image'] as String,
  );

  Map<String, dynamic> toJson() => {
    'title': title,
    'snippet': snippet,
    'image': image,
  };

  /// The page title. Always present when a preview exists at all.
  final String title;

  /// A description of the page, when the page offered one.
  final String? snippet;

  /// An image, already re-hosted by the server when it has a filehost configured.
  final String? image;
}

/// Who we are on this connection.
class LocalUser {
  const LocalUser({
    required this.nick,
    required this.account,
    required this.modes,
    required this.metadata,
    required this.away,
  });

  factory LocalUser.fromJson(Map<String, dynamic> json) => LocalUser(
    nick: json['nick'] as String,
    account: json['account'] == null ? null : json['account'] as String,
    modes: json['modes'] as String,
    metadata: (json['metadata'] as Map<String, dynamic>).map((k, v) => MapEntry(k, v as String)),
    away: json['away'] == null ? null : json['away'] as String,
  );

  Map<String, dynamic> toJson() => {
    'nick': nick,
    'account': account,
    'modes': modes,
    'metadata': metadata.map((k, v) => MapEntry(k, v)),
    'away': away,
  };

  /// Our current nick.
  final String nick;

  /// The account we authenticated as.
  final String? account;

  /// Our user modes.
  final String modes;

  /// Metadata the server holds, such as `display-name`, `color`, `avatar` and `bot`.
  /// These are plain `draft/metadata-2` keys with no vendor prefix, despite everything else Obby
  /// adds being namespaced.
  final Map<String, String> metadata;

  /// Our away message, when we are away.
  final String? away;
}

/// What one member holds in one channel.
/// Only the channel-specific part. Who they are, what account they hold and whether they are away
/// are the same everywhere, so they live once on [`Person`] rather than being copied into every
/// channel they are in and drifting apart.
class Membership {
  const Membership({
    required this.prefixes,
  });

  factory Membership.fromJson(Map<String, dynamic> json) => Membership(
    prefixes: json['prefixes'] as String,
  );

  Map<String, dynamic> toJson() => {
    'prefixes': prefixes,
  };

  /// The prefix characters they hold here, highest rank first.
  final String prefixes;
}

/// Where a message is ordered and how it is found again.
/// Ordering is by the server's timestamp, with a monotonic sequence number breaking ties. A tie
/// broken by arrival order alone is what the reference client relies on, and it only holds there
/// because of an incidental property of the sort it uses.
class MessageKey {
  const MessageKey({
    required this.time_ms,
    required this.seq,
  });

  factory MessageKey.fromJson(Map<String, dynamic> json) => MessageKey(
    time_ms: json['time_ms'] as int,
    seq: json['seq'] as int,
  );

  Map<String, dynamic> toJson() => {
    'time_ms': time_ms,
    'seq': seq,
  };

  /// Milliseconds since the epoch, from `server-time` when the server sent one.
  final int time_ms;

  /// Assigned in arrival order, unique for the life of the connection.
  final int seq;
}

/// What kind of thing happened.
sealed class MessageKind {
  const MessageKind();

  Map<String, dynamic> toJson();

  factory MessageKind.fromJson(Map<String, dynamic> json) {
    final tag = json['type'] as String;
    return switch (tag) {
      'privmsg' => MessageKindPrivmsg.fromJson(json),
      'notice' => MessageKindNotice.fromJson(json),
      'ctcp' => MessageKindCtcp.fromJson(json),
      'tagmsg' => MessageKindTagmsg.fromJson(json),
      'join' => MessageKindJoin.fromJson(json),
      'part' => MessageKindPart.fromJson(json),
      'quit' => MessageKindQuit.fromJson(json),
      'kick' => MessageKindKick.fromJson(json),
      'nick' => MessageKindNick.fromJson(json),
      'topic' => MessageKindTopic.fromJson(json),
      'mode' => MessageKindMode.fromJson(json),
      _ => throw ArgumentError.value(tag, 'type', 'unknown MessageKind variant'),
    };
  }
}

class MessageKindPrivmsg extends MessageKind {
  const MessageKindPrivmsg();

  factory MessageKindPrivmsg.fromJson(Map<String, dynamic> json) => const MessageKindPrivmsg();

  @override
  Map<String, dynamic> toJson() => {'type': 'privmsg'};
}

class MessageKindNotice extends MessageKind {
  const MessageKindNotice();

  factory MessageKindNotice.fromJson(Map<String, dynamic> json) => const MessageKindNotice();

  @override
  Map<String, dynamic> toJson() => {'type': 'notice'};
}

class MessageKindCtcp extends MessageKind {
  const MessageKindCtcp({
    required this.command,
  });

  factory MessageKindCtcp.fromJson(Map<String, dynamic> json) => MessageKindCtcp(
    command: json['command'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'ctcp',
    'command': command,
  };

  /// The CTCP command, uppercased, such as `ACTION`.
  final String command;
}

class MessageKindTagmsg extends MessageKind {
  const MessageKindTagmsg();

  factory MessageKindTagmsg.fromJson(Map<String, dynamic> json) => const MessageKindTagmsg();

  @override
  Map<String, dynamic> toJson() => {'type': 'tagmsg'};
}

class MessageKindJoin extends MessageKind {
  const MessageKindJoin();

  factory MessageKindJoin.fromJson(Map<String, dynamic> json) => const MessageKindJoin();

  @override
  Map<String, dynamic> toJson() => {'type': 'join'};
}

class MessageKindPart extends MessageKind {
  const MessageKindPart();

  factory MessageKindPart.fromJson(Map<String, dynamic> json) => const MessageKindPart();

  @override
  Map<String, dynamic> toJson() => {'type': 'part'};
}

class MessageKindQuit extends MessageKind {
  const MessageKindQuit();

  factory MessageKindQuit.fromJson(Map<String, dynamic> json) => const MessageKindQuit();

  @override
  Map<String, dynamic> toJson() => {'type': 'quit'};
}

class MessageKindKick extends MessageKind {
  const MessageKindKick({
    required this.target,
  });

  factory MessageKindKick.fromJson(Map<String, dynamic> json) => MessageKindKick(
    target: json['target'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'kick',
    'target': target,
  };

  /// Who was removed.
  final String target;
}

class MessageKindNick extends MessageKind {
  const MessageKindNick({
    required this.new_nick,
  });

  factory MessageKindNick.fromJson(Map<String, dynamic> json) => MessageKindNick(
    new_nick: json['new_nick'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'nick',
    'new_nick': new_nick,
  };

  /// What they changed it to.
  final String new_nick;
}

class MessageKindTopic extends MessageKind {
  const MessageKindTopic();

  factory MessageKindTopic.fromJson(Map<String, dynamic> json) => const MessageKindTopic();

  @override
  Map<String, dynamic> toJson() => {'type': 'topic'};
}

class MessageKindMode extends MessageKind {
  const MessageKindMode();

  factory MessageKindMode.fromJson(Map<String, dynamic> json) => const MessageKindMode();

  @override
  Map<String, dynamic> toJson() => {'type': 'mode'};
}

/// The messages of one channel or conversation, ordered and bounded.
class MessageLog {
  const MessageLog({
    required this.messages,
    required this.by_msgid,
    required this.retention,
  });

  factory MessageLog.fromJson(Map<String, dynamic> json) => MessageLog(
    messages: (json['messages'] as List).map((e) => ChatMessage.fromJson(e as Map<String, dynamic>)).toList(),
    by_msgid: (json['by_msgid'] as Map<String, dynamic>).map((k, v) => MapEntry(k, MessageKey.fromJson(v as Map<String, dynamic>))),
    retention: json['retention'] as int,
  );

  Map<String, dynamic> toJson() => {
    'messages': messages.map((e) => e.toJson()).toList(),
    'by_msgid': by_msgid.map((k, v) => MapEntry(k, v.toJson())),
    'retention': retention,
  };

  final List<ChatMessage> messages;

  final Map<String, MessageKey> by_msgid;

  final int retention;
}

/// Where a message came from, as sent in the `:`-prefixed source.
/// A server sends its own name; a client's message arrives as `nick!user@host`, though a server may
/// send only the nick.
class MessageSource {
  const MessageSource({
    required this.name,
    required this.user,
    required this.host,
  });

  factory MessageSource.fromJson(Map<String, dynamic> json) => MessageSource(
    name: json['name'] as String,
    user: json['user'] == null ? null : json['user'] as String,
    host: json['host'] == null ? null : json['host'] as String,
  );

  Map<String, dynamic> toJson() => {
    'name': name,
    'user': user,
    'host': host,
  };

  /// The nick, or the server name when there is no `!` or `@`.
  final String name;

  /// The user part, when the source is a full hostmask.
  final String? user;

  /// The host part, when present.
  final String? host;
}

/// One message tag. A tag with an empty value is the same as a tag with no value, so both parse to
/// `value: None`.
class MessageTag {
  const MessageTag({
    required this.key,
    required this.value,
  });

  factory MessageTag.fromJson(Map<String, dynamic> json) => MessageTag(
    key: json['key'] as String,
    value: json['value'] == null ? null : json['value'] as String,
  );

  Map<String, dynamic> toJson() => {
    'key': key,
    'value': value,
  };

  /// The tag name, including a leading `+` on a client-only tag and any vendor prefix.
  final String key;

  /// The unescaped value.
  final String? value;
}

/// The tag section of a message, in the order it arrived.
/// Order is kept rather than folded into a map because a round trip has to reproduce the line, and
/// because a server may legally send the same key twice.
typedef MessageTags = List<MessageTag>;

/// Everything the connection knows.
class Model {
  const Model({
    required this.me,
    required this.channels,
    required this.conversations,
    required this.people,
    required this.whois,
    required this.retention,
    required this.next_seq,
  });

  factory Model.fromJson(Map<String, dynamic> json) => Model(
    me: LocalUser.fromJson(json['me'] as Map<String, dynamic>),
    channels: (json['channels'] as Map<String, dynamic>).map((k, v) => MapEntry(k, Channel.fromJson(v as Map<String, dynamic>))),
    conversations: (json['conversations'] as Map<String, dynamic>).map((k, v) => MapEntry(k, Conversation.fromJson(v as Map<String, dynamic>))),
    people: (json['people'] as Map<String, dynamic>).map((k, v) => MapEntry(k, Person.fromJson(v as Map<String, dynamic>))),
    whois: (json['whois'] as Map<String, dynamic>).map((k, v) => MapEntry(k, Whois.fromJson(v as Map<String, dynamic>))),
    retention: json['retention'] as int,
    next_seq: json['next_seq'] as int,
  );

  Map<String, dynamic> toJson() => {
    'me': me.toJson(),
    'channels': channels.map((k, v) => MapEntry(k, v.toJson())),
    'conversations': conversations.map((k, v) => MapEntry(k, v.toJson())),
    'people': people.map((k, v) => MapEntry(k, v.toJson())),
    'whois': whois.map((k, v) => MapEntry(k, v.toJson())),
    'retention': retention,
    'next_seq': next_seq,
  };

  /// Who we are.
  final LocalUser me;

  final Map<CaseFolded, Channel> channels;

  final Map<CaseFolded, Conversation> conversations;

  final Map<CaseFolded, Person> people;

  final Map<CaseFolded, Whois> whois;

  final int retention;

  final int next_seq;
}

/// What changed, for a host that wants to react without diffing the whole model.
sealed class ModelChange {
  const ModelChange();

  Map<String, dynamic> toJson();

  factory ModelChange.fromJson(Map<String, dynamic> json) {
    final tag = json['type'] as String;
    return switch (tag) {
      'message_added' => ModelChangeMessageAdded.fromJson(json),
      'channel_joined' => ModelChangeChannelJoined.fromJson(json),
      'channel_parted' => ModelChangeChannelParted.fromJson(json),
      'channel_members_changed' => ModelChangeChannelMembersChanged.fromJson(json),
      'channel_topic_changed' => ModelChangeChannelTopicChanged.fromJson(json),
      'nick_changed' => ModelChangeNickChanged.fromJson(json),
      'channel_modes_changed' => ModelChangeChannelModesChanged.fromJson(json),
      'read_marker_moved' => ModelChangeReadMarkerMoved.fromJson(json),
      'message_reacted' => ModelChangeMessageReacted.fromJson(json),
      'message_redacted' => ModelChangeMessageRedacted.fromJson(json),
      'metadata_changed' => ModelChangeMetadataChanged.fromJson(json),
      'whois_received' => ModelChangeWhoisReceived.fromJson(json),
      'channel_renamed' => ModelChangeChannelRenamed.fromJson(json),
      _ => throw ArgumentError.value(tag, 'type', 'unknown ModelChange variant'),
    };
  }
}

class ModelChangeMessageAdded extends ModelChange {
  const ModelChangeMessageAdded({
    required this.target,
    required this.key,
  });

  factory ModelChangeMessageAdded.fromJson(Map<String, dynamic> json) => ModelChangeMessageAdded(
    target: json['target'] as String,
    key: MessageKey.fromJson(json['key'] as Map<String, dynamic>),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'message_added',
    'target': target,
    'key': key.toJson(),
  };

  /// The channel or nick it belongs to, as the server spells it.
  final String target;

  /// Where it sits in that target's log.
  final MessageKey key;
}

class ModelChangeChannelJoined extends ModelChange {
  const ModelChangeChannelJoined({
    required this.channel,
  });

  factory ModelChangeChannelJoined.fromJson(Map<String, dynamic> json) => ModelChangeChannelJoined(
    channel: json['channel'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'channel_joined',
    'channel': channel,
  };

  /// The channel.
  final String channel;
}

class ModelChangeChannelParted extends ModelChange {
  const ModelChangeChannelParted({
    required this.channel,
  });

  factory ModelChangeChannelParted.fromJson(Map<String, dynamic> json) => ModelChangeChannelParted(
    channel: json['channel'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'channel_parted',
    'channel': channel,
  };

  /// The channel.
  final String channel;
}

class ModelChangeChannelMembersChanged extends ModelChange {
  const ModelChangeChannelMembersChanged({
    required this.channel,
  });

  factory ModelChangeChannelMembersChanged.fromJson(Map<String, dynamic> json) => ModelChangeChannelMembersChanged(
    channel: json['channel'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'channel_members_changed',
    'channel': channel,
  };

  /// The channel.
  final String channel;
}

class ModelChangeChannelTopicChanged extends ModelChange {
  const ModelChangeChannelTopicChanged({
    required this.channel,
  });

  factory ModelChangeChannelTopicChanged.fromJson(Map<String, dynamic> json) => ModelChangeChannelTopicChanged(
    channel: json['channel'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'channel_topic_changed',
    'channel': channel,
  };

  /// The channel.
  final String channel;
}

class ModelChangeNickChanged extends ModelChange {
  const ModelChangeNickChanged({
    required this.from,
    required this.to,
  });

  factory ModelChangeNickChanged.fromJson(Map<String, dynamic> json) => ModelChangeNickChanged(
    from: json['from'] as String,
    to: json['to'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'nick_changed',
    'from': from,
    'to': to,
  };

  /// What they were called.
  final String from;

  /// What they are called now.
  final String to;
}

class ModelChangeChannelModesChanged extends ModelChange {
  const ModelChangeChannelModesChanged({
    required this.channel,
  });

  factory ModelChangeChannelModesChanged.fromJson(Map<String, dynamic> json) => ModelChangeChannelModesChanged(
    channel: json['channel'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'channel_modes_changed',
    'channel': channel,
  };

  /// The channel.
  final String channel;
}

class ModelChangeReadMarkerMoved extends ModelChange {
  const ModelChangeReadMarkerMoved({
    required this.target,
  });

  factory ModelChangeReadMarkerMoved.fromJson(Map<String, dynamic> json) => ModelChangeReadMarkerMoved(
    target: json['target'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'read_marker_moved',
    'target': target,
  };

  /// The channel or person.
  final String target;
}

class ModelChangeMessageReacted extends ModelChange {
  const ModelChangeMessageReacted({
    required this.target,
    required this.msgid,
  });

  factory ModelChangeMessageReacted.fromJson(Map<String, dynamic> json) => ModelChangeMessageReacted(
    target: json['target'] as String,
    msgid: json['msgid'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'message_reacted',
    'target': target,
    'msgid': msgid,
  };

  /// Where the message is.
  final String target;

  /// The message reacted to.
  final String msgid;
}

class ModelChangeMessageRedacted extends ModelChange {
  const ModelChangeMessageRedacted({
    required this.target,
    required this.msgid,
  });

  factory ModelChangeMessageRedacted.fromJson(Map<String, dynamic> json) => ModelChangeMessageRedacted(
    target: json['target'] as String,
    msgid: json['msgid'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'message_redacted',
    'target': target,
    'msgid': msgid,
  };

  /// Where the message was.
  final String target;

  /// The message deleted.
  final String msgid;
}

class ModelChangeMetadataChanged extends ModelChange {
  const ModelChangeMetadataChanged({
    required this.target,
    required this.key,
  });

  factory ModelChangeMetadataChanged.fromJson(Map<String, dynamic> json) => ModelChangeMetadataChanged(
    target: json['target'] as String,
    key: json['key'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'metadata_changed',
    'target': target,
    'key': key,
  };

  /// Whose metadata changed.
  final String target;

  /// The key that changed.
  final String key;
}

class ModelChangeWhoisReceived extends ModelChange {
  const ModelChangeWhoisReceived({
    required this.nick,
  });

  factory ModelChangeWhoisReceived.fromJson(Map<String, dynamic> json) => ModelChangeWhoisReceived(
    nick: json['nick'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'whois_received',
    'nick': nick,
  };

  /// Who it describes.
  final String nick;
}

class ModelChangeChannelRenamed extends ModelChange {
  const ModelChangeChannelRenamed({
    required this.from,
    required this.to,
  });

  factory ModelChangeChannelRenamed.fromJson(Map<String, dynamic> json) => ModelChangeChannelRenamed(
    from: json['from'] as String,
    to: json['to'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'channel_renamed',
    'from': from,
    'to': to,
  };

  /// What it was called.
  final String from;

  /// What it is called now.
  final String to;
}

/// Something the host needs to know about.
/// Events are drained with [`Client::poll_event`] rather than delivered through a callback, because
/// a callback needs a different lifetime, threading and re-entrancy contract in every language this
/// engine is bound into.
sealed class ObbyEvent {
  const ObbyEvent();

  Map<String, dynamic> toJson();

  factory ObbyEvent.fromJson(Map<String, dynamic> json) {
    final tag = json['type'] as String;
    return switch (tag) {
      'capabilities_acknowledged' => ObbyEventCapabilitiesAcknowledged.fromJson(json),
      'registered' => ObbyEventRegistered.fromJson(json),
      'isupport_token' => ObbyEventIsupportToken.fromJson(json),
      'logged_in' => ObbyEventLoggedIn.fromJson(json),
      'sasl_failed' => ObbyEventSaslFailed.fromJson(json),
      'nick_in_use' => ObbyEventNickInUse.fromJson(json),
      'model_changed' => ObbyEventModelChanged.fromJson(json),
      'link_dead' => ObbyEventLinkDead.fromJson(json),
      'reconnect_after' => ObbyEventReconnectAfter.fromJson(json),
      'reconnect_abandoned' => ObbyEventReconnectAbandoned.fromJson(json),
      'command_timed_out' => ObbyEventCommandTimedOut.fromJson(json),
      'allowed_commands_changed' => ObbyEventAllowedCommandsChanged.fromJson(json),
      'bots_changed' => ObbyEventBotsChanged.fromJson(json),
      'auth_token' => ObbyEventAuthToken.fromJson(json),
      'voice' => ObbyEventVoice.fromJson(json),
      'typing_changed' => ObbyEventTypingChanged.fromJson(json),
      'presence_changed' => ObbyEventPresenceChanged.fromJson(json),
      'server_reply' => ObbyEventServerReply.fromJson(json),
      'raw_line' => ObbyEventRawLine.fromJson(json),
      _ => throw ArgumentError.value(tag, 'type', 'unknown ObbyEvent variant'),
    };
  }
}

class ObbyEventCapabilitiesAcknowledged extends ObbyEvent {
  const ObbyEventCapabilitiesAcknowledged({
    required this.names,
  });

  factory ObbyEventCapabilitiesAcknowledged.fromJson(Map<String, dynamic> json) => ObbyEventCapabilitiesAcknowledged(
    names: (json['names'] as List).map((e) => e as String).toList(),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'capabilities_acknowledged',
    'names': names.map((e) => e).toList(),
  };

  /// The capability names, as acknowledged.
  final List<String> names;
}

class ObbyEventRegistered extends ObbyEvent {
  const ObbyEventRegistered({
    required this.nick,
  });

  factory ObbyEventRegistered.fromJson(Map<String, dynamic> json) => ObbyEventRegistered(
    nick: json['nick'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'registered',
    'nick': nick,
  };

  /// The nick the server actually gave us, which may differ from the one we asked for.
  final String nick;
}

class ObbyEventIsupportToken extends ObbyEvent {
  const ObbyEventIsupportToken({
    required this.token,
    required this.value,
  });

  factory ObbyEventIsupportToken.fromJson(Map<String, dynamic> json) => ObbyEventIsupportToken(
    token: json['token'] as String,
    value: json['value'] == null ? null : json['value'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'isupport_token',
    'token': token,
    'value': value,
  };

  /// The token name, such as `CHANMODES`.
  final String token;

  /// Its value, absent for a boolean token, present and empty for `TOKEN=`.
  final String? value;
}

class ObbyEventLoggedIn extends ObbyEvent {
  const ObbyEventLoggedIn({
    required this.account,
  });

  factory ObbyEventLoggedIn.fromJson(Map<String, dynamic> json) => ObbyEventLoggedIn(
    account: json['account'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'logged_in',
    'account': account,
  };

  /// The account the server logged us in as.
  final String account;
}

class ObbyEventSaslFailed extends ObbyEvent {
  const ObbyEventSaslFailed({
    required this.reason,
  });

  factory ObbyEventSaslFailed.fromJson(Map<String, dynamic> json) => ObbyEventSaslFailed(
    reason: SaslFailure.fromWire(json['reason'] as String),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'sasl_failed',
    'reason': reason.wire,
  };

  /// Why it ended.
  final SaslFailure reason;
}

class ObbyEventNickInUse extends ObbyEvent {
  const ObbyEventNickInUse({
    required this.refused,
    required this.trying,
  });

  factory ObbyEventNickInUse.fromJson(Map<String, dynamic> json) => ObbyEventNickInUse(
    refused: json['refused'] as String,
    trying: json['trying'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'nick_in_use',
    'refused': refused,
    'trying': trying,
  };

  /// The nick that was refused.
  final String refused;

  /// What is being tried instead.
  final String trying;
}

class ObbyEventModelChanged extends ObbyEvent {
  const ObbyEventModelChanged({
    required this.change,
  });

  factory ObbyEventModelChanged.fromJson(Map<String, dynamic> json) => ObbyEventModelChanged(
    change: ModelChange.fromJson(json['change'] as Map<String, dynamic>),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'model_changed',
    'change': change.toJson(),
  };

  /// What changed.
  final ModelChange change;
}

class ObbyEventLinkDead extends ObbyEvent {
  const ObbyEventLinkDead();

  factory ObbyEventLinkDead.fromJson(Map<String, dynamic> json) => const ObbyEventLinkDead();

  @override
  Map<String, dynamic> toJson() => {'type': 'link_dead'};
}

class ObbyEventReconnectAfter extends ObbyEvent {
  const ObbyEventReconnectAfter({
    required this.after_ms,
  });

  factory ObbyEventReconnectAfter.fromJson(Map<String, dynamic> json) => ObbyEventReconnectAfter(
    after_ms: json['after_ms'] as int,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'reconnect_after',
    'after_ms': after_ms,
  };

  /// How long the host should wait first.
  final int after_ms;
}

class ObbyEventReconnectAbandoned extends ObbyEvent {
  const ObbyEventReconnectAbandoned();

  factory ObbyEventReconnectAbandoned.fromJson(Map<String, dynamic> json) => const ObbyEventReconnectAbandoned();

  @override
  Map<String, dynamic> toJson() => {'type': 'reconnect_abandoned'};
}

class ObbyEventCommandTimedOut extends ObbyEvent {
  const ObbyEventCommandTimedOut({
    required this.command,
  });

  factory ObbyEventCommandTimedOut.fromJson(Map<String, dynamic> json) => ObbyEventCommandTimedOut(
    command: json['command'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'command_timed_out',
    'command': command,
  };

  /// The command that went unanswered.
  final String command;
}

class ObbyEventAllowedCommandsChanged extends ObbyEvent {
  const ObbyEventAllowedCommandsChanged();

  factory ObbyEventAllowedCommandsChanged.fromJson(Map<String, dynamic> json) => const ObbyEventAllowedCommandsChanged();

  @override
  Map<String, dynamic> toJson() => {'type': 'allowed_commands_changed'};
}

class ObbyEventBotsChanged extends ObbyEvent {
  const ObbyEventBotsChanged({
    required this.nick,
  });

  factory ObbyEventBotsChanged.fromJson(Map<String, dynamic> json) => ObbyEventBotsChanged(
    nick: json['nick'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'bots_changed',
    'nick': nick,
  };

  /// The bot the server told us about.
  final String nick;
}

class ObbyEventAuthToken extends ObbyEvent {
  const ObbyEventAuthToken({
    required this.service,
    required this.endpoint,
    required this.token,
  });

  factory ObbyEventAuthToken.fromJson(Map<String, dynamic> json) => ObbyEventAuthToken(
    service: json['service'] as String,
    endpoint: json['endpoint'] as String,
    token: json['token'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'auth_token',
    'service': service,
    'endpoint': endpoint,
    'token': token,
  };

  /// The service it is for, as the server spells it.
  final String service;

  /// Where to present it.
  final String endpoint;

  /// The token itself.
  final String token;
}

class ObbyEventVoice extends ObbyEvent {
  const ObbyEventVoice({
    required this.channel,
    required this.signal,
  });

  factory ObbyEventVoice.fromJson(Map<String, dynamic> json) => ObbyEventVoice(
    channel: json['channel'] as String,
    signal: VoiceSignal.fromJson(json['signal'] as Map<String, dynamic>),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'voice',
    'channel': channel,
    'signal': signal.toJson(),
  };

  /// The channel the room belongs to.
  final String channel;

  /// The frame.
  final VoiceSignal signal;
}

class ObbyEventTypingChanged extends ObbyEvent {
  const ObbyEventTypingChanged({
    required this.target,
    required this.nick,
    required this.active,
  });

  factory ObbyEventTypingChanged.fromJson(Map<String, dynamic> json) => ObbyEventTypingChanged(
    target: json['target'] as String,
    nick: json['nick'] as String,
    active: json['active'] as bool,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'typing_changed',
    'target': target,
    'nick': nick,
    'active': active,
  };

  /// The channel or conversation they are composing in.
  final String target;

  /// Who.
  final String nick;

  /// True when they are composing now.
  final bool active;
}

class ObbyEventPresenceChanged extends ObbyEvent {
  const ObbyEventPresenceChanged({
    required this.nick,
    required this.online,
  });

  factory ObbyEventPresenceChanged.fromJson(Map<String, dynamic> json) => ObbyEventPresenceChanged(
    nick: json['nick'] as String,
    online: json['online'] as bool,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'presence_changed',
    'nick': nick,
    'online': online,
  };

  /// Who.
  final String nick;

  /// True when they are here now.
  final bool online;
}

class ObbyEventServerReply extends ObbyEvent {
  const ObbyEventServerReply({
    required this.severity,
    required this.command,
    required this.code,
    required this.context,
    required this.text,
  });

  factory ObbyEventServerReply.fromJson(Map<String, dynamic> json) => ObbyEventServerReply(
    severity: Severity.fromWire(json['severity'] as String),
    command: json['command'] as String,
    code: json['code'] as String,
    context: (json['context'] as List).map((e) => e as String).toList(),
    text: json['text'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'server_reply',
    'severity': severity.wire,
    'command': command,
    'code': code,
    'context': context.map((e) => e).toList(),
    'text': text,
  };

  /// How serious it is.
  final Severity severity;

  /// The command it concerns, or `*` when the server did not say.
  final String command;

  /// The machine-readable code, such as `ACCOUNT_REQUIRED_TO_CONNECT`.
  final String code;

  /// Any further parameters the server gave, before the description.
  final List<String> context;

  /// The human-readable description.
  final String text;
}

class ObbyEventRawLine extends ObbyEvent {
  const ObbyEventRawLine({
    required this.message,
  });

  factory ObbyEventRawLine.fromJson(Map<String, dynamic> json) => ObbyEventRawLine(
    message: RawMessage.fromJson(json['message'] as Map<String, dynamic>),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'raw_line',
    'message': message.toJson(),
  };

  /// The parsed line.
  final RawMessage message;
}

/// The two states an intent frame like `mic` or `hand` toggles between.
enum OnOff {
  on,
  off;

  static OnOff fromWire(String wire) => OnOff.values.byName(wire);

  String get wire => name;
}

/// Someone we know about, held once however many channels we share.
class Person {
  const Person({
    required this.nick,
    required this.account,
    required this.away,
    required this.bot,
    required this.username,
    required this.host,
    required this.realname,
    required this.operator,
    required this.metadata,
  });

  factory Person.fromJson(Map<String, dynamic> json) => Person(
    nick: json['nick'] as String,
    account: json['account'] == null ? null : json['account'] as String,
    away: json['away'] == null ? null : json['away'] as String,
    bot: json['bot'] as bool,
    username: json['username'] == null ? null : json['username'] as String,
    host: json['host'] == null ? null : json['host'] as String,
    realname: json['realname'] == null ? null : json['realname'] as String,
    operator: json['operator'] as bool,
    metadata: (json['metadata'] as Map<String, dynamic>).map((k, v) => MapEntry(k, v as String)),
  );

  Map<String, dynamic> toJson() => {
    'nick': nick,
    'account': account,
    'away': away,
    'bot': bot,
    'username': username,
    'host': host,
    'realname': realname,
    'operator': operator,
    'metadata': metadata.map((k, v) => MapEntry(k, v)),
  };

  /// Their nick, as they spell it.
  final String nick;

  /// The account they are logged in as.
  final String? account;

  /// Their away message, when they are away.
  final String? away;

  /// True when the server marks them as a bot.
  final bool bot;

  /// Their username, from WHO or a hostmask.
  final String? username;

  /// Their host, from WHO or a hostmask.
  final String? host;

  /// Their realname, from WHO.
  final String? realname;

  /// True when the server marks them as an operator.
  final bool operator;

  /// Metadata the server holds, such as `display-name`, `color` and `avatar`.
  /// These are plain `draft/metadata-2` keys with no vendor prefix, despite everything else Obby
  /// adds being namespaced.
  final Map<String, String> metadata;
}

/// A parsed protocol line.
/// The types are owned rather than borrowed from the input. A borrowed `Message<'a>` would parse
/// faster, but every consumer of this crate reaches it across a language boundary that cannot carry
/// a Rust lifetime, so the copy has to happen somewhere and here is the only place it happens once.
class RawMessage {
  const RawMessage({
    required this.tags,
    required this.source,
    required this.command,
    required this.params,
  });

  factory RawMessage.fromJson(Map<String, dynamic> json) => RawMessage(
    tags: (json['tags'] as List).map((e) => MessageTag.fromJson(e as Map<String, dynamic>)).toList(),
    source: json['source'] == null ? null : MessageSource.fromJson(json['source'] as Map<String, dynamic>),
    command: json['command'] as String,
    params: (json['params'] as List).map((e) => e as String).toList(),
  );

  Map<String, dynamic> toJson() => {
    'tags': tags.map((e) => e.toJson()).toList(),
    'source': source?.toJson(),
    'command': command,
    'params': params.map((e) => e).toList(),
  };

  /// The tag section, empty when the line carried no `@`.
  final MessageTags tags;

  /// The source, when the line carried one.
  final MessageSource? source;

  /// The command or three-digit numeric, as it arrived. Commands are case-insensitive on the wire,
  /// so compare with [`Message::is`] rather than `==`.
  final String command;

  /// The parameters, with the trailing parameter last and its `:` removed.
  final List<String> params;
}

/// What to authenticate with.
sealed class SaslCredentials {
  const SaslCredentials();

  Map<String, dynamic> toJson();

  factory SaslCredentials.fromJson(Map<String, dynamic> json) {
    final tag = json['mechanism'] as String;
    return switch (tag) {
      'plain' => SaslCredentialsPlain.fromJson(json),
      'external' => SaslCredentialsExternal.fromJson(json),
      'scram' => SaslCredentialsScram.fromJson(json),
      _ => throw ArgumentError.value(tag, 'mechanism', 'unknown SaslCredentials variant'),
    };
  }
}

class SaslCredentialsPlain extends SaslCredentials {
  const SaslCredentialsPlain({
    required this.username,
    required this.password,
  });

  factory SaslCredentialsPlain.fromJson(Map<String, dynamic> json) => SaslCredentialsPlain(
    username: json['username'] as String,
    password: json['password'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'mechanism': 'plain',
    'username': username,
    'password': password,
  };

  /// The account to log in as.
  final String username;

  /// Its password.
  final String password;
}

class SaslCredentialsExternal extends SaslCredentials {
  const SaslCredentialsExternal();

  factory SaslCredentialsExternal.fromJson(Map<String, dynamic> json) => const SaslCredentialsExternal();

  @override
  Map<String, dynamic> toJson() => {'mechanism': 'external'};
}

class SaslCredentialsScram extends SaslCredentials {
  const SaslCredentialsScram({
    required this.username,
    required this.password,
    required this.nonce,
  });

  factory SaslCredentialsScram.fromJson(Map<String, dynamic> json) => SaslCredentialsScram(
    username: json['username'] as String,
    password: json['password'] as String,
    nonce: json['nonce'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'mechanism': 'scram',
    'username': username,
    'password': password,
    'nonce': nonce,
  };

  /// The account to log in as.
  final String username;

  /// Its password.
  final String password;

  /// Unpredictable bytes, never reused. The core has no entropy source, so the host supplies
  /// this, and reusing one destroys the replay protection the mechanism exists for.
  final String nonce;
}

/// Why authentication ended without succeeding.
enum SaslFailure {
  rejected,
  too_long,
  aborted,
  already_authenticated,
  no_shared_mechanism,
  server_not_verified;

  static SaslFailure fromWire(String wire) => SaslFailure.values.byName(wire);

  String get wire => name;
}

/// How serious a `standard-replies` message is.
enum Severity {
  fail,
  warn,
  note;

  static Severity fromWire(String wire) => Severity.values.byName(wire);

  String get wire => name;
}

/// TURN/STUN credentials the SFU hands us on `joined`.
/// These are short-lived, and nothing in the `joined` handshake or anywhere else in the
/// signalling plane ever refreshes them mid-call. A call that outlives them loses its relay path
/// with no warning;
/// whoever integrates this signalling plane needs to leave and rejoin (or otherwise trigger a
/// fresh `joined`) before that happens, since nothing here does it automatically.
class TurnCredentials {
  const TurnCredentials({
    required this.urls,
    required this.username,
    required this.password,
  });

  factory TurnCredentials.fromJson(Map<String, dynamic> json) => TurnCredentials(
    urls: (json['urls'] as List).map((e) => e as String).toList(),
    username: json['username'] as String,
    password: json['password'] as String,
  );

  Map<String, dynamic> toJson() => {
    'urls': urls.map((e) => e).toList(),
    'username': username,
    'password': password,
  };

  /// The TURN/STUN server URLs to try, in order.
  final List<String> urls;

  /// The short-lived TURN username.
  final String username;

  /// The short-lived TURN password.
  final String password;
}

/// Whether we are still composing a message.
enum TypingState {
  active,
  paused,
  done;

  static TypingState fromWire(String wire) => TypingState.values.byName(wire);

  String get wire => name;
}

/// One participant's state within a [`Room`].
/// Every toggle is [`OnOff`] rather than `bool`: this is the same distinction clippy's own
/// `struct_excessive_bools` lint asks for (six independent flags read equally well as a state
/// machine's cases), and reusing `OnOff` rather than inventing six near-identical two-variant
/// enums keeps it to one type.
class VoiceParticipant {
  const VoiceParticipant({
    required this.nick,
    required this.role,
    required this.mic,
    required this.video,
    required this.speaking,
    required this.deaf,
    required this.screen,
    required this.hand,
  });

  factory VoiceParticipant.fromJson(Map<String, dynamic> json) => VoiceParticipant(
    nick: json['nick'] as String,
    role: VoiceRole.fromWire(json['role'] as String),
    mic: OnOff.fromWire(json['mic'] as String),
    video: OnOff.fromWire(json['video'] as String),
    speaking: OnOff.fromWire(json['speaking'] as String),
    deaf: OnOff.fromWire(json['deaf'] as String),
    screen: OnOff.fromWire(json['screen'] as String),
    hand: OnOff.fromWire(json['hand'] as String),
  );

  Map<String, dynamic> toJson() => {
    'nick': nick,
    'role': role.wire,
    'mic': mic.wire,
    'video': video.wire,
    'speaking': speaking.wire,
    'deaf': deaf.wire,
    'screen': screen.wire,
    'hand': hand.wire,
  };

  /// Their nick as the server spells it, since the map that holds them is keyed by a fold that
  /// throws that spelling away.
  final String nick;

  /// Whether they may publish, decided by the room kind and, in a `$` room, whether the
  /// server named them a streamer.
  final VoiceRole role;

  /// Microphone on.
  final OnOff mic;

  /// Camera on.
  final OnOff video;

  /// The voice-activity flag the last `presence` reported.
  final OnOff speaking;

  /// Not receiving room audio.
  final OnOff deaf;

  /// Screen share active.
  final OnOff screen;

  /// Hand raised.
  final OnOff hand;
}

/// The `state` a `presence` notification carries.
/// One wire `type: "presence"` actually carries three incompatible shapes: a membership change (`Joined`/`Left`), a toggle
/// (`On`/`Off`, read together with [`Signal::Presence`]'s `kind`), or an activity flag
/// (`Speaking`/`Silent`/`DeafOn`/`DeafOff`, which carries no `kind` at all).
enum VoicePresence {
  joined,
  left,
  on,
  off,
  speaking,
  silent,
  deaf_on,
  deaf_off;

  static VoicePresence fromWire(String wire) => VoicePresence.values.byName(wire);

  String get wire => name;
}

/// Whether a room participant may publish audio and video, or only receive it.
enum VoiceRole {
  publisher,
  viewer;

  static VoiceRole fromWire(String wire) => VoiceRole.values.byName(wire);

  String get wire => name;
}

/// The state of one voice room: who is in it, their kind of channel, and every participant's
/// mic, video, speaking, deaf, screen and hand state and role.
class VoiceRoom {
  const VoiceRoom({
    required this.channel,
    required this.kind,
    required this.participants,
    required this.turn,
  });

  factory VoiceRoom.fromJson(Map<String, dynamic> json) => VoiceRoom(
    channel: json['channel'] as String,
    kind: VoiceRoomKind.fromWire(json['kind'] as String),
    participants: (json['participants'] as Map<String, dynamic>).map((k, v) => MapEntry(k, VoiceParticipant.fromJson(v as Map<String, dynamic>))),
    turn: json['turn'] == null ? null : TurnCredentials.fromJson(json['turn'] as Map<String, dynamic>),
  );

  Map<String, dynamic> toJson() => {
    'channel': channel,
    'kind': kind.wire,
    'participants': participants.map((k, v) => MapEntry(k, v.toJson())),
    'turn': turn?.toJson(),
  };

  /// The channel this room's signalling is scoped to.
  final String channel;

  /// Whether every member publishes, or only the streamer and whoever they promote.
  final VoiceRoomKind kind;

  /// Every known participant, keyed by their folded nick.
  final Map<CaseFolded, VoiceParticipant> participants;

  /// The TURN credentials the SFU handed us on `joined`, if it has yet.
  final TurnCredentials? turn;
}

/// Who may publish in a voice room, decided by the channel's sigil.
enum VoiceRoomKind {
  publish,
  stream;

  static VoiceRoomKind fromWire(String wire) => VoiceRoomKind.values.byName(wire);

  String get wire => name;
}

/// One `+obsidianirc/rtc` signalling frame.
/// Every variant is one JSON object's `type`. The published
/// <https://github.com/obbyworld/extensions/blob/main/voice.md> documents only 9 of these, the
/// wire carries 19, and this enum follows the wire. Outbound intent and inbound notification are modelled as distinct shapes where the
/// wire actually distinguishes them (`mic`/`video`/`screen`/`hand`/`speaking`/`silent`/`deaf`
/// versus the `presence` they get rebroadcast as; `promote`/`demote` versus `role`), rather than
/// collapsed into one type as the published table's prose implies.
sealed class VoiceSignal {
  const VoiceSignal();

  Map<String, dynamic> toJson();

  factory VoiceSignal.fromJson(Map<String, dynamic> json) {
    final tag = json['type'] as String;
    return switch (tag) {
      'join' => VoiceSignalJoin.fromJson(json),
      'leave' => VoiceSignalLeave.fromJson(json),
      'joined' => VoiceSignalJoined.fromJson(json),
      'offer' => VoiceSignalOffer.fromJson(json),
      'answer' => VoiceSignalAnswer.fromJson(json),
      'ice' => VoiceSignalIce.fromJson(json),
      'presence' => VoiceSignalPresence.fromJson(json),
      'mic' => VoiceSignalMic.fromJson(json),
      'video' => VoiceSignalVideo.fromJson(json),
      'screen' => VoiceSignalScreen.fromJson(json),
      'hand' => VoiceSignalHand.fromJson(json),
      'deaf' => VoiceSignalDeaf.fromJson(json),
      'speaking' => VoiceSignalSpeaking.fromJson(json),
      'silent' => VoiceSignalSilent.fromJson(json),
      'react' => VoiceSignalReact.fromJson(json),
      'promote' => VoiceSignalPromote.fromJson(json),
      'demote' => VoiceSignalDemote.fromJson(json),
      'role' => VoiceSignalRole.fromJson(json),
      'error' => VoiceSignalError.fromJson(json),
      _ => throw ArgumentError.value(tag, 'type', 'unknown VoiceSignal variant'),
    };
  }
}

class VoiceSignalJoin extends VoiceSignal {
  const VoiceSignalJoin({
    required this.channel,
  });

  factory VoiceSignalJoin.fromJson(Map<String, dynamic> json) => VoiceSignalJoin(
    channel: json['channel'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'join',
    'channel': channel,
  };

  /// The channel to join.
  final String channel;
}

class VoiceSignalLeave extends VoiceSignal {
  const VoiceSignalLeave({
    required this.channel,
  });

  factory VoiceSignalLeave.fromJson(Map<String, dynamic> json) => VoiceSignalLeave(
    channel: json['channel'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'leave',
    'channel': channel,
  };

  /// The channel to leave.
  final String channel;
}

class VoiceSignalJoined extends VoiceSignal {
  const VoiceSignalJoined({
    required this.members,
    required this.mode,
    required this.role,
    required this.streamers,
    required this.turn,
    required this.tracks,
  });

  factory VoiceSignalJoined.fromJson(Map<String, dynamic> json) => VoiceSignalJoined(
    members: (json['members'] as List).map((e) => e as String).toList(),
    mode: json['mode'] == null ? null : VoiceRoomKind.fromWire(json['mode'] as String),
    role: json['role'] == null ? null : VoiceRole.fromWire(json['role'] as String),
    streamers: json['streamers'] == null ? null : (json['streamers'] as List).map((e) => e as String).toList(),
    turn: json['turn'] == null ? null : TurnCredentials.fromJson(json['turn'] as Map<String, dynamic>),
    tracks: json['tracks'] == null ? null : (json['tracks'] as List).map((e) => VoiceTrackHint.fromJson(e as Map<String, dynamic>)).toList(),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'joined',
    'members': members.map((e) => e).toList(),
    'mode': mode?.wire,
    'role': role?.wire,
    'streamers': streamers?.map((e) => e).toList(),
    'turn': turn?.toJson(),
    'tracks': tracks?.map((e) => e.toJson()).toList(),
  };

  /// Every current member's nick.
  final List<String> members;

  /// The room's kind, present only for a `$` channel.
  final VoiceRoomKind? mode;

  /// The role granted to us specifically, present only for a `$` channel.
  final VoiceRole? role;

  /// Who currently publishes, for a `$` channel.
  final List<String>? streamers;

  /// The TURN credentials for this call.
  final TurnCredentials? turn;

  /// Hints mapping media lines to the members they belong to.
  final List<VoiceTrackHint>? tracks;
}

class VoiceSignalOffer extends VoiceSignal {
  const VoiceSignalOffer({
    required this.sdp,
    required this.tracks,
    required this.chunk,
  });

  factory VoiceSignalOffer.fromJson(Map<String, dynamic> json) => VoiceSignalOffer(
    sdp: json['sdp'] as String,
    tracks: json['tracks'] == null ? null : (json['tracks'] as List).map((e) => VoiceTrackHint.fromJson(e as Map<String, dynamic>)).toList(),
    chunk: json['chunk'] == null ? null : ChunkMeta.fromJson(json['chunk'] as Map<String, dynamic>),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'offer',
    'sdp': sdp,
    'tracks': tracks?.map((e) => e.toJson()).toList(),
    'chunk': chunk?.toJson(),
  };

  /// The offer SDP, or one slice of it when `chunk` is set.
  final String sdp;

  /// Track-attribution hints, carried only on chunk 0 or an unchunked offer.
  final List<VoiceTrackHint>? tracks;

  /// Set when this frame is one of several chunks sharing an id.
  final ChunkMeta? chunk;
}

class VoiceSignalAnswer extends VoiceSignal {
  const VoiceSignalAnswer({
    required this.sdp,
    required this.chunk,
  });

  factory VoiceSignalAnswer.fromJson(Map<String, dynamic> json) => VoiceSignalAnswer(
    sdp: json['sdp'] as String,
    chunk: json['chunk'] == null ? null : ChunkMeta.fromJson(json['chunk'] as Map<String, dynamic>),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'answer',
    'sdp': sdp,
    'chunk': chunk?.toJson(),
  };

  /// The answer SDP, or one slice of it when `chunk` is set.
  final String sdp;

  /// Set when this frame is one of several chunks sharing an id.
  final ChunkMeta? chunk;
}

class VoiceSignalIce extends VoiceSignal {
  const VoiceSignalIce({
    required this.cand,
    required this.mid,
    required this.mlineidx,
  });

  factory VoiceSignalIce.fromJson(Map<String, dynamic> json) => VoiceSignalIce(
    cand: json['cand'] as String,
    mid: json['mid'] == null ? null : json['mid'] as String,
    mlineidx: json['mlineidx'] == null ? null : json['mlineidx'] as int,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'ice',
    'cand': cand,
    'mid': mid,
    'mlineidx': mlineidx,
  };

  /// The candidate string.
  final String cand;

  /// The media line it applies to.
  final String? mid;

  /// The media line's index, when `mid` is absent.
  final int? mlineidx;
}

class VoiceSignalPresence extends VoiceSignal {
  const VoiceSignalPresence({
    required this.member,
    required this.state,
    required this.kind,
    required this.role,
  });

  factory VoiceSignalPresence.fromJson(Map<String, dynamic> json) => VoiceSignalPresence(
    member: json['member'] as String,
    state: VoicePresence.fromWire(json['state'] as String),
    kind: json['kind'] == null ? null : VoiceToggle.fromWire(json['kind'] as String),
    role: json['role'] == null ? null : VoiceRole.fromWire(json['role'] as String),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'presence',
    'member': member,
    'state': state.wire,
    'kind': kind?.wire,
    'role': role?.wire,
  };

  /// Who this is about.
  final String member;

  /// What changed.
  final VoicePresence state;

  /// Which toggle, when `state` is [`PresenceState::On`] or [`PresenceState::Off`].
  final VoiceToggle? kind;

  /// The role granted, when `state` is [`PresenceState::Joined`] in a `$` room.
  final VoiceRole? role;
}

class VoiceSignalMic extends VoiceSignal {
  const VoiceSignalMic({
    required this.state,
  });

  factory VoiceSignalMic.fromJson(Map<String, dynamic> json) => VoiceSignalMic(
    state: OnOff.fromWire(json['state'] as String),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'mic',
    'state': state.wire,
  };

  /// The new state.
  final OnOff state;
}

class VoiceSignalVideo extends VoiceSignal {
  const VoiceSignalVideo({
    required this.state,
  });

  factory VoiceSignalVideo.fromJson(Map<String, dynamic> json) => VoiceSignalVideo(
    state: OnOff.fromWire(json['state'] as String),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'video',
    'state': state.wire,
  };

  /// The new state.
  final OnOff state;
}

class VoiceSignalScreen extends VoiceSignal {
  const VoiceSignalScreen({
    required this.state,
  });

  factory VoiceSignalScreen.fromJson(Map<String, dynamic> json) => VoiceSignalScreen(
    state: OnOff.fromWire(json['state'] as String),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'screen',
    'state': state.wire,
  };

  /// The new state.
  final OnOff state;
}

class VoiceSignalHand extends VoiceSignal {
  const VoiceSignalHand({
    required this.state,
  });

  factory VoiceSignalHand.fromJson(Map<String, dynamic> json) => VoiceSignalHand(
    state: OnOff.fromWire(json['state'] as String),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'hand',
    'state': state.wire,
  };

  /// The new state.
  final OnOff state;
}

class VoiceSignalDeaf extends VoiceSignal {
  const VoiceSignalDeaf({
    required this.state,
  });

  factory VoiceSignalDeaf.fromJson(Map<String, dynamic> json) => VoiceSignalDeaf(
    state: OnOff.fromWire(json['state'] as String),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'deaf',
    'state': state.wire,
  };

  /// The new state.
  final OnOff state;
}

class VoiceSignalSpeaking extends VoiceSignal {
  const VoiceSignalSpeaking();

  factory VoiceSignalSpeaking.fromJson(Map<String, dynamic> json) => const VoiceSignalSpeaking();

  @override
  Map<String, dynamic> toJson() => {'type': 'speaking'};
}

class VoiceSignalSilent extends VoiceSignal {
  const VoiceSignalSilent();

  factory VoiceSignalSilent.fromJson(Map<String, dynamic> json) => const VoiceSignalSilent();

  @override
  Map<String, dynamic> toJson() => {'type': 'silent'};
}

class VoiceSignalReact extends VoiceSignal {
  const VoiceSignalReact({
    required this.member,
    required this.emoji,
  });

  factory VoiceSignalReact.fromJson(Map<String, dynamic> json) => VoiceSignalReact(
    member: json['member'] == null ? null : json['member'] as String,
    emoji: json['emoji'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'react',
    'member': member,
    'emoji': emoji,
  };

  /// Who reacted, present only on the inbound broadcast.
  final String? member;

  /// The emoji.
  final String emoji;
}

class VoiceSignalPromote extends VoiceSignal {
  const VoiceSignalPromote({
    required this.target,
  });

  factory VoiceSignalPromote.fromJson(Map<String, dynamic> json) => VoiceSignalPromote(
    target: json['target'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'promote',
    'target': target,
  };

  /// The member to promote.
  final String target;
}

class VoiceSignalDemote extends VoiceSignal {
  const VoiceSignalDemote({
    required this.target,
  });

  factory VoiceSignalDemote.fromJson(Map<String, dynamic> json) => VoiceSignalDemote(
    target: json['target'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'demote',
    'target': target,
  };

  /// The member to demote.
  final String target;
}

class VoiceSignalRole extends VoiceSignal {
  const VoiceSignalRole({
    required this.member,
    required this.role,
  });

  factory VoiceSignalRole.fromJson(Map<String, dynamic> json) => VoiceSignalRole(
    member: json['member'] as String,
    role: VoiceRole.fromWire(json['role'] as String),
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'role',
    'member': member,
    'role': role.wire,
  };

  /// Whose role changed.
  final String member;

  /// Their new role.
  final VoiceRole role;
}

class VoiceSignalError extends VoiceSignal {
  const VoiceSignalError({
    required this.error,
  });

  factory VoiceSignalError.fromJson(Map<String, dynamic> json) => VoiceSignalError(
    error: json['error'] == null ? null : json['error'] as String,
  );

  @override
  Map<String, dynamic> toJson() => {
    'type': 'error',
    'error': error,
  };

  /// A human-readable reason, when the server gave one.
  final String? error;
}

/// Which per-participant toggle a `presence` notification reports, for its toggle sub-shape.
enum VoiceToggle {
  mic,
  video,
  screen,
  hand;

  static VoiceToggle fromWire(String wire) => VoiceToggle.values.byName(wire);

  String get wire => name;
}

/// A hint from the SFU mapping one negotiated media line to the member it belongs to.
/// The SFU sends mid-to-member hints so an inbound track can be attributed to the right member
/// when the SDP's own `msid` is missing or unreliable. This is the minimal shape that serves that
/// purpose; a real server may send more fields, which this simply ignores on decode.
class VoiceTrackHint {
  const VoiceTrackHint({
    required this.mid,
    required this.member,
  });

  factory VoiceTrackHint.fromJson(Map<String, dynamic> json) => VoiceTrackHint(
    mid: json['mid'] as String,
    member: json['member'] as String,
  );

  Map<String, dynamic> toJson() => {
    'mid': mid,
    'member': member,
  };

  /// The SDP media line identifier this hint names.
  final String mid;

  /// The member that media line belongs to.
  final String member;
}

/// Who we are watching, and whether each is online.
class WatchList {
  const WatchList({
    required this.watching,
    required this.online,
  });

  factory WatchList.fromJson(Map<String, dynamic> json) => WatchList(
    watching: (json['watching'] as List).map((e) => e as CaseFolded).toList(),
    online: (json['online'] as List).map((e) => e as CaseFolded).toList(),
  );

  Map<String, dynamic> toJson() => {
    'watching': watching.map((e) => e).toList(),
    'online': online.map((e) => e).toList(),
  };

  final List<CaseFolded> watching;

  final List<CaseFolded> online;
}

/// What a `WHOIS` said about someone.
/// A reply is nine numerics that arrive one at a time, so they are collected here and reported once,
/// when the closing `318` lands. A host that reacted to each numeric would redraw a profile card
/// nine times and show eight incomplete ones.
class Whois {
  const Whois({
    required this.nick,
    required this.username,
    required this.host,
    required this.realname,
    required this.server,
    required this.server_info,
    required this.operator,
    required this.idle_secs,
    required this.signon_ms,
    required this.channels,
    required this.account,
    required this.actual_host,
    required this.secure,
    required this.complete,
  });

  factory Whois.fromJson(Map<String, dynamic> json) => Whois(
    nick: json['nick'] as String,
    username: json['username'] == null ? null : json['username'] as String,
    host: json['host'] == null ? null : json['host'] as String,
    realname: json['realname'] == null ? null : json['realname'] as String,
    server: json['server'] == null ? null : json['server'] as String,
    server_info: json['server_info'] == null ? null : json['server_info'] as String,
    operator: json['operator'] == null ? null : json['operator'] as String,
    idle_secs: json['idle_secs'] == null ? null : json['idle_secs'] as int,
    signon_ms: json['signon_ms'] == null ? null : json['signon_ms'] as int,
    channels: (json['channels'] as List).map((e) => e as String).toList(),
    account: json['account'] == null ? null : json['account'] as String,
    actual_host: json['actual_host'] == null ? null : json['actual_host'] as String,
    secure: json['secure'] as bool,
    complete: json['complete'] as bool,
  );

  Map<String, dynamic> toJson() => {
    'nick': nick,
    'username': username,
    'host': host,
    'realname': realname,
    'server': server,
    'server_info': server_info,
    'operator': operator,
    'idle_secs': idle_secs,
    'signon_ms': signon_ms,
    'channels': channels.map((e) => e).toList(),
    'account': account,
    'actual_host': actual_host,
    'secure': secure,
    'complete': complete,
  };

  /// Their nick, as the server spells it.
  final String nick;

  /// Their username, from `311`.
  final String? username;

  /// Their host, from `311`.
  final String? host;

  /// Their realname, from `311`.
  final String? realname;

  /// The server they are on, from `312`.
  final String? server;

  /// What that server calls itself, from `312`.
  final String? server_info;

  /// How the server describes their operator privileges, from `313`, when they have any.
  final String? operator;

  /// How long they have been idle, from `317`.
  final int? idle_secs;

  /// When they connected, in milliseconds since the Unix epoch, from `317`.
  final int? signon_ms;

  /// The channels they are in, keeping the prefix each one carries, from `319`.
  final List<String> channels;

  /// The account they are logged in as, from `330`.
  final String? account;

  /// Where they are connecting from, as the server words it, from `338` or `378`.
  final String? actual_host;

  /// True when the server said the connection is over TLS, from `671`.
  final bool secure;

  /// True once the closing `318` arrived and there is nothing more to come.
  final bool complete;
}
