// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The set of commands the server says we may currently use.
 *
 * The server pushes this on connect and again whenever it changes, such as after an `OPER`. A
 * batch carries additions and removals together, so both are applied at once.
 */
export type AllowedCommands = { available: Array<string>, };

/**
 * What the server knows about a bot in a channel.
 */
export type Bot = { 
/**
 * The bot's nick.
 */
nick: string, 
/**
 * The identifier the server gave it.
 */
id: string | null, 
/**
 * True when an operator configured this bot, rather than it registering itself.
 *
 * Only a configured bot may claim a privileged command name. A bot that registered itself has
 * those names stripped, so it cannot shadow `oper` or `identify`.
 */
from_config: boolean, 
/**
 * The commands it offers.
 */
commands: Array<BotCommand>, };

/**
 * One command a bot offers.
 */
export type BotCommand = { 
/**
 * What to type, without its leading slash.
 */
name: string, 
/**
 * What it does.
 */
description: string | null, };

/**
 * The bots we know about, keyed by their folded nick.
 */
export type BotRegistry = { known: { [key in string]?: Bot }, };

/**
 * What the server offers and what we hold.
 */
export type Capabilities = { available: { [key in string]?: string | null }, acknowledged: { [key in string]?: string | null }, 
/**
 * Capabilities we asked for and are still waiting on. Registration cannot finish while this is
 * non-empty, because `CAP END` before the last reply loses the capability.
 */
pending: Array<string>, };

/**
 * One capability the server advertised, with the value it carried if any.
 */
export type Capability = { 
/**
 * The capability name, without any `=value` suffix.
 */
name: string, 
/**
 * The value, for capabilities like `sasl=PLAIN,EXTERNAL` that carry one.
 */
value: string | null, };

/**
 * A nick or channel name folded under a server's casemapping.
 *
 * Every map keyed by a nick or a channel is keyed by this type, so that a raw `String` can never be
 * used as an identity by accident.
 *
 * The mapping that produced it is not stored. Two `CaseFolded` values are only comparable when they
 * came from the same connection, which is the only place they are ever used together.
 */
export type CaseFolded = string;

/**
 * A channel we are in.
 */
export type Channel = { 
/**
 * The name as the server spells it.
 */
name: string, 
/**
 * The topic, when one is set.
 */
topic: string | null, 
/**
 * Who set the topic and when.
 */
topic_by: string | null, 
/**
 * Channel modes currently set, with their arguments.
 */
modes: { [key in string]?: string | null }, 
/**
 * Who is in it.
 */
members: { [key in CaseFolded]?: Membership }, 
/**
 * What was said.
 */
log: MessageLog, 
/**
 * Messages since the last read marker.
 */
unread: number, 
/**
 * Unread messages that mention us.
 */
mentions: number, 
/**
 * Metadata the server holds, such as `display-name`, `color`, `avatar` and `bot`.
 *
 * These are plain `draft/metadata-2` keys with no vendor prefix, despite everything else Obby
 * adds being namespaced.
 */
metadata: { [key in string]?: string }, 
/**
 * The read marker timestamp the server last confirmed.
 */
read_marker: string | null, 
/**
 * Who is composing a message here right now.
 */
typing: Array<CaseFolded>, 
/**
 * Modes by their name rather than their letter, from `draft/named-modes`.
 *
 * A letter means nothing without the server telling you what it does, and two servers spell
 * the same feature differently. The names are stable, so this is what a user interface should
 * show and what a setting should be keyed by.
 */
named_modes: { [key in string]?: string | null }, };

/**
 * One message, as the model holds it.
 */
export type ChatMessage = { 
/**
 * Where it sits in the log.
 */
key: MessageKey, 
/**
 * The network-unique id, when the server assigned one.
 */
msgid: string | null, 
/**
 * Who sent it, as they spell their own nick.
 */
sender: string, 
/**
 * What kind of event it is.
 */
kind: MessageKind, 
/**
 * The body, empty for events that have none.
 */
text: string, 
/**
 * The account the sender was logged in as, from `account-tag`.
 */
account: string | null, 
/**
 * True when this arrived inside a history batch rather than live.
 */
historical: boolean, 
/**
 * True when this is our own message coming back through `echo-message`.
 */
own: boolean, 
/**
 * The message this one replies to, from the `+reply` tag.
 *
 * The server is inconsistent about the spelling and sends `+reply` from one module and
 * `+draft/reply` from another, so both are accepted on the way in.
 */
reply_to: string | null, 
/**
 * Reactions, keyed by the emoji, holding who reacted.
 */
reactions: { [key in string]?: Array<string> }, 
/**
 * A preview of the first link in this message, when the server built one.
 */
link_preview: LinkPreview | null, 
/**
 * True once the message was redacted. The original is kept, because throwing it away leaves no
 * way to show who redacted what.
 */
redacted: boolean, };

/**
 * The chunk-correlation fields riding alongside a split `sdp` value.
 */
export type ChunkMeta = { 
/**
 * The id every chunk of one split frame shares.
 */
id: string, 
/**
 * This chunk's 0-based position.
 */
seq: number, 
/**
 * How many chunks the split frame was cut into.
 */
total: number, };

/**
 * Something to do on this connection.
 */
export type Command = { "type": "join", 
/**
 * The channel to join.
 */
channel: string, 
/**
 * Its key, when it has one.
 */
key: string | null, } | { "type": "part", 
/**
 * The channel to leave.
 */
channel: string, 
/**
 * Why, shown to the others in it.
 */
reason: string | null, } | { "type": "send_message", 
/**
 * Where to say it.
 */
target: string, 
/**
 * What to say.
 */
text: string, } | { "type": "send_notice", 
/**
 * Where to send it.
 */
target: string, 
/**
 * What to send.
 */
text: string, } | { "type": "send_action", 
/**
 * Where to send it.
 */
target: string, 
/**
 * What we are doing.
 */
text: string, } | { "type": "set_nick", 
/**
 * The nick to take.
 */
nick: string, } | { "type": "set_topic", 
/**
 * The channel.
 */
channel: string, 
/**
 * The new topic, or nothing to clear it.
 */
topic: string | null, } | { "type": "set_away", 
/**
 * The away message, or nothing to come back.
 */
message: string | null, } | { "type": "set_typing", 
/**
 * Who we are typing to.
 */
target: string, 
/**
 * How far along we are.
 */
state: TypingState, } | { "type": "add_reaction", 
/**
 * The channel or person the message is in.
 */
target: string, 
/**
 * The message reacted to.
 */
msgid: string, 
/**
 * The emoji.
 */
emoji: string, } | { "type": "remove_reaction", 
/**
 * The channel or person the message is in.
 */
target: string, 
/**
 * The message.
 */
msgid: string, 
/**
 * The emoji to remove.
 */
emoji: string, } | { "type": "redact_message", 
/**
 * Where the message is.
 */
target: string, 
/**
 * The message to delete.
 */
msgid: string, 
/**
 * Why, when the server wants a reason.
 */
reason: string | null, } | { "type": "mark_read", 
/**
 * The channel or person.
 */
target: string, 
/**
 * The last message read, in milliseconds since the Unix epoch. The engine writes the
 * `server-time` the wire wants.
 */
at_ms: number, } | { "type": "fetch_history", 
/**
 * The channel or person.
 */
target: string, 
/**
 * Fetch messages older than the message with this id.
 */
before_msgid: string | null, 
/**
 * How many to ask for.
 */
limit: number, } | { "type": "set_metadata", 
/**
 * The key, such as `display-name`, `color` or `avatar`.
 */
key: string, 
/**
 * The value, or nothing to clear the key.
 */
value: string | null, } | { "type": "subscribe_metadata", 
/**
 * The keys to watch.
 */
keys: Array<string>, } | { "type": "watch_nicks", 
/**
 * The nicks to watch.
 */
nicks: Array<string>, } | { "type": "unwatch_nicks", 
/**
 * The nicks to stop watching.
 */
nicks: Array<string>, } | { "type": "send_voice_signal", 
/**
 * The channel to signal in.
 */
channel: string, 
/**
 * The frame. The engine encodes it as the JSON that travels in the tag.
 */
signal: VoiceSignal, } | { "type": "quit", 
/**
 * Why.
 */
reason: string | null, } | { "type": "send_raw_line", 
/**
 * The line, without its terminator.
 */
line: string, };

/**
 * What a host needs to give the engine before it can connect.
 *
 * Every field but the nick has a default, so a host deserialising one only has to supply what it
 * actually cares about. An empty username or realname is filled in from the nick.
 */
export type Config = { 
/**
 * The nick to register with.
 */
nick: string, 
/**
 * The username sent in `USER`. Defaults to the nick.
 */
username?: string, 
/**
 * The realname sent in `USER`. Defaults to the nick.
 */
realname?: string, 
/**
 * The server password, sent as `PASS` before anything else.
 */
password?: string, 
/**
 * What to authenticate with, when the server offers `sasl`.
 */
sasl?: SaslCredentials, 
/**
 * How many messages each channel and conversation keeps.
 */
retention?: number, 
/**
 * Nicks to fall back through when the server says ours is taken during registration.
 *
 * Registration stalls forever if nobody answers a 433, so the engine walks this list and then
 * starts appending underscores rather than leaving the connection hung.
 */
alt_nicks?: Array<string>, };

/**
 * How far the connection has got.
 */
export type ConnectionPhase = "disconnected" | "negotiating" | "registering" | "registered";

/**
 * A private conversation with one other person.
 */
export type Conversation = { 
/**
 * Their nick, as they spell it.
 */
nick: string, 
/**
 * What was said.
 */
log: MessageLog, 
/**
 * Messages since the last read marker.
 */
unread: number, 
/**
 * The read marker timestamp the server last confirmed.
 */
read_marker: string | null, 
/**
 * Who is composing a message here right now.
 */
typing: Array<CaseFolded>, };

/**
 * An invitation link to the network or to one channel.
 */
export type Invitation = { 
/**
 * The identifier used to delete it.
 */
share_id: string, 
/**
 * The channel it joins, or nothing when it invites to the network.
 */
channel: string | null, 
/**
 * The link itself.
 */
url: string, 
/**
 * When it was made, as the server spells it.
 */
created: string | null, 
/**
 * How many people have used it.
 */
redeemed: number, 
/**
 * What it is for.
 */
description: string | null, };

/**
 * A preview of a link someone posted, built by the server and attached to the message.
 *
 * The server fetches the page; a client never does. There is no capability to negotiate, and the
 * server refuses these tags from any sender but itself, so a peer cannot forge one.
 */
export type LinkPreview = { 
/**
 * The page title. Always present when a preview exists at all.
 */
title: string, 
/**
 * A description of the page, when the page offered one.
 */
snippet: string | null, 
/**
 * An image, already re-hosted by the server when it has a filehost configured.
 */
image: string | null, };

/**
 * Who we are on this connection.
 */
export type LocalUser = { 
/**
 * Our current nick.
 */
nick: string, 
/**
 * The account we authenticated as.
 */
account: string | null, 
/**
 * Our user modes.
 */
modes: string, 
/**
 * Metadata the server holds, such as `display-name`, `color`, `avatar` and `bot`.
 *
 * These are plain `draft/metadata-2` keys with no vendor prefix, despite everything else Obby
 * adds being namespaced.
 */
metadata: { [key in string]?: string }, 
/**
 * Our away message, when we are away.
 */
away: string | null, };

/**
 * What one member holds in one channel.
 *
 * Only the channel-specific part. Who they are, what account they hold and whether they are away
 * are the same everywhere, so they live once on [`Person`] rather than being copied into every
 * channel they are in and drifting apart.
 */
export type Membership = { 
/**
 * The prefix characters they hold here, highest rank first.
 */
prefixes: string, };

/**
 * Where a message is ordered and how it is found again.
 *
 * Ordering is by the server's timestamp, with a monotonic sequence number breaking ties. A tie
 * broken by arrival order alone is what the reference client relies on, and it only holds there
 * because of an incidental property of the sort it uses.
 */
export type MessageKey = { 
/**
 * Milliseconds since the epoch, from `server-time` when the server sent one.
 */
time_ms: number, 
/**
 * Assigned in arrival order, unique for the life of the connection.
 */
seq: number, };

/**
 * What kind of thing happened.
 */
export type MessageKind = { "type": "privmsg" } | { "type": "notice" } | { "type": "ctcp", 
/**
 * The CTCP command, uppercased, such as `ACTION`.
 */
command: string, } | { "type": "tagmsg" } | { "type": "join" } | { "type": "part" } | { "type": "quit" } | { "type": "kick", 
/**
 * Who was removed.
 */
target: string, } | { "type": "nick", 
/**
 * What they changed it to.
 */
new_nick: string, } | { "type": "topic" } | { "type": "mode" };

/**
 * The messages of one channel or conversation, ordered and bounded.
 */
export type MessageLog = { messages: Array<ChatMessage>, by_msgid: { [key in string]?: MessageKey }, retention: number, };

/**
 * Where a message came from, as sent in the `:`-prefixed source.
 *
 * A server sends its own name; a client's message arrives as `nick!user@host`, though a server may
 * send only the nick.
 */
export type MessageSource = { 
/**
 * The nick, or the server name when there is no `!` or `@`.
 */
name: string, 
/**
 * The user part, when the source is a full hostmask.
 */
user: string | null, 
/**
 * The host part, when present.
 */
host: string | null, };

/**
 * One message tag. A tag with an empty value is the same as a tag with no value, so both parse to
 * `value: None`.
 */
export type MessageTag = { 
/**
 * The tag name, including a leading `+` on a client-only tag and any vendor prefix.
 */
key: string, 
/**
 * The unescaped value.
 */
value: string | null, };

/**
 * The tag section of a message, in the order it arrived.
 *
 * Order is kept rather than folded into a map because a round trip has to reproduce the line, and
 * because a server may legally send the same key twice.
 */
export type MessageTags = Array<MessageTag>;

/**
 * Everything the connection knows.
 */
export type Model = { 
/**
 * Who we are.
 */
me: LocalUser, channels: { [key in CaseFolded]?: Channel }, conversations: { [key in CaseFolded]?: Conversation }, people: { [key in CaseFolded]?: Person }, retention: number, next_seq: number, };

/**
 * What changed, for a host that wants to react without diffing the whole model.
 */
export type ModelChange = { "type": "message_added", 
/**
 * The channel or nick it belongs to, as the server spells it.
 */
target: string, 
/**
 * Where it sits in that target's log.
 */
key: MessageKey, } | { "type": "channel_joined", 
/**
 * The channel.
 */
channel: string, } | { "type": "channel_parted", 
/**
 * The channel.
 */
channel: string, } | { "type": "channel_members_changed", 
/**
 * The channel.
 */
channel: string, } | { "type": "channel_topic_changed", 
/**
 * The channel.
 */
channel: string, } | { "type": "nick_changed", 
/**
 * What they were called.
 */
from: string, 
/**
 * What they are called now.
 */
to: string, } | { "type": "channel_modes_changed", 
/**
 * The channel.
 */
channel: string, } | { "type": "read_marker_moved", 
/**
 * The channel or person.
 */
target: string, } | { "type": "message_reacted", 
/**
 * Where the message is.
 */
target: string, 
/**
 * The message reacted to.
 */
msgid: string, } | { "type": "message_redacted", 
/**
 * Where the message was.
 */
target: string, 
/**
 * The message deleted.
 */
msgid: string, } | { "type": "metadata_changed", 
/**
 * Whose metadata changed.
 */
target: string, 
/**
 * The key that changed.
 */
key: string, };

/**
 * Something the host needs to know about.
 *
 * Events are drained with [`Client::poll_event`] rather than delivered through a callback, because
 * a callback needs a different lifetime, threading and re-entrancy contract in every language this
 * engine is bound into.
 */
export type ObbyEvent = { "type": "capabilities_acknowledged", 
/**
 * The capability names, as acknowledged.
 */
names: Array<string>, } | { "type": "registered", 
/**
 * The nick the server actually gave us, which may differ from the one we asked for.
 */
nick: string, } | { "type": "isupport_token", 
/**
 * The token name, such as `CHANMODES`.
 */
token: string, 
/**
 * Its value, absent for a boolean token, present and empty for `TOKEN=`.
 */
value: string | null, } | { "type": "logged_in", 
/**
 * The account the server logged us in as.
 */
account: string, } | { "type": "sasl_failed", 
/**
 * Why it ended.
 */
reason: SaslFailure, } | { "type": "nick_in_use", 
/**
 * The nick that was refused.
 */
refused: string, 
/**
 * What is being tried instead.
 */
trying: string, } | { "type": "model_changed", 
/**
 * What changed.
 */
change: ModelChange, } | { "type": "link_dead" } | { "type": "reconnect_after", 
/**
 * How long the host should wait first.
 */
after_ms: number, } | { "type": "reconnect_abandoned" } | { "type": "command_timed_out", 
/**
 * The command that went unanswered.
 */
command: string, } | { "type": "allowed_commands_changed" } | { "type": "voice", 
/**
 * The channel the room belongs to.
 */
channel: string, 
/**
 * The frame.
 */
signal: VoiceSignal, } | { "type": "typing_changed", 
/**
 * The channel or conversation they are composing in.
 */
target: string, 
/**
 * Who.
 */
nick: string, 
/**
 * True when they are composing now.
 */
active: boolean, } | { "type": "presence_changed", 
/**
 * Who.
 */
nick: string, 
/**
 * True when they are here now.
 */
online: boolean, } | { "type": "server_reply", 
/**
 * How serious it is.
 */
severity: Severity, 
/**
 * The command it concerns, or `*` when the server did not say.
 */
command: string, 
/**
 * The machine-readable code, such as `ACCOUNT_REQUIRED_TO_CONNECT`.
 */
code: string, 
/**
 * Any further parameters the server gave, before the description.
 */
context: Array<string>, 
/**
 * The human-readable description.
 */
text: string, } | { "type": "raw_line", 
/**
 * The parsed line.
 */
message: RawMessage, };

/**
 * The two states an intent frame like `mic` or `hand` toggles between.
 */
export type OnOff = "on" | "off";

/**
 * Someone we know about, held once however many channels we share.
 */
export type Person = { 
/**
 * Their nick, as they spell it.
 */
nick: string, 
/**
 * The account they are logged in as.
 */
account: string | null, 
/**
 * Their away message, when they are away.
 */
away: string | null, 
/**
 * True when the server marks them as a bot.
 */
bot: boolean, 
/**
 * Their username, from WHO or a hostmask.
 */
username: string | null, 
/**
 * Their host, from WHO or a hostmask.
 */
host: string | null, 
/**
 * Their realname, from WHO.
 */
realname: string | null, 
/**
 * True when the server marks them as an operator.
 */
operator: boolean, 
/**
 * Metadata the server holds, such as `display-name`, `color` and `avatar`.
 *
 * These are plain `draft/metadata-2` keys with no vendor prefix, despite everything else Obby
 * adds being namespaced.
 */
metadata: { [key in string]?: string }, };

/**
 * A parsed protocol line.
 *
 * The types are owned rather than borrowed from the input. A borrowed `Message<'a>` would parse
 * faster, but every consumer of this crate reaches it across a language boundary that cannot carry
 * a Rust lifetime, so the copy has to happen somewhere and here is the only place it happens once.
 */
export type RawMessage = { 
/**
 * The tag section, empty when the line carried no `@`.
 */
tags: MessageTags, 
/**
 * The source, when the line carried one.
 */
source: MessageSource | null, 
/**
 * The command or three-digit numeric, as it arrived. Commands are case-insensitive on the wire,
 * so compare with [`Message::is`] rather than `==`.
 */
command: string, 
/**
 * The parameters, with the trailing parameter last and its `:` removed.
 */
params: Array<string>, };

/**
 * What to authenticate with.
 */
export type SaslCredentials = { "mechanism": "plain", 
/**
 * The account to log in as.
 */
username: string, 
/**
 * Its password.
 */
password: string, } | { "mechanism": "external" } | { "mechanism": "scram", 
/**
 * The account to log in as.
 */
username: string, 
/**
 * Its password.
 */
password: string, 
/**
 * Unpredictable bytes, never reused. The core has no entropy source, so the host supplies
 * this, and reusing one destroys the replay protection the mechanism exists for.
 */
nonce: string, };

/**
 * Why authentication ended without succeeding.
 */
export type SaslFailure = "rejected" | "too_long" | "aborted" | "already_authenticated" | "no_shared_mechanism" | "server_not_verified";

/**
 * How serious a `standard-replies` message is.
 */
export type Severity = "fail" | "warn" | "note";

/**
 * TURN/STUN credentials the SFU hands us on `joined`.
 *
 * These are short-lived, and nothing in the `joined` handshake or anywhere else in the
 * signalling plane ever refreshes them mid-call. A call that outlives them loses its relay path
 * with no warning;
 * whoever integrates this signalling plane needs to leave and rejoin (or otherwise trigger a
 * fresh `joined`) before that happens, since nothing here does it automatically.
 */
export type TurnCredentials = { 
/**
 * The TURN/STUN server URLs to try, in order.
 */
urls: Array<string>, 
/**
 * The short-lived TURN username.
 */
username: string, 
/**
 * The short-lived TURN password.
 */
password: string, };

/**
 * Whether we are still composing a message.
 */
export type TypingState = "active" | "paused" | "done";

/**
 * One participant's state within a [`Room`].
 *
 * Every toggle is [`OnOff`] rather than `bool`: this is the same distinction clippy's own
 * `struct_excessive_bools` lint asks for (six independent flags read equally well as a state
 * machine's cases), and reusing `OnOff` rather than inventing six near-identical two-variant
 * enums keeps it to one type.
 */
export type VoiceParticipant = { 
/**
 * Their nick as the server spells it, since the map that holds them is keyed by a fold that
 * throws that spelling away.
 */
nick: string, 
/**
 * Whether they may publish, decided by the room kind and, in a `$` room, whether the
 * server named them a streamer.
 */
role: VoiceRole, 
/**
 * Microphone on.
 */
mic: OnOff, 
/**
 * Camera on.
 */
video: OnOff, 
/**
 * The voice-activity flag the last `presence` reported.
 */
speaking: OnOff, 
/**
 * Not receiving room audio.
 */
deaf: OnOff, 
/**
 * Screen share active.
 */
screen: OnOff, 
/**
 * Hand raised.
 */
hand: OnOff, };

/**
 * The `state` a `presence` notification carries.
 *
 * One wire `type: "presence"` actually carries three incompatible shapes: a membership change (`Joined`/`Left`), a toggle
 * (`On`/`Off`, read together with [`Signal::Presence`]'s `kind`), or an activity flag
 * (`Speaking`/`Silent`/`DeafOn`/`DeafOff`, which carries no `kind` at all).
 */
export type VoicePresence = "joined" | "left" | "on" | "off" | "speaking" | "silent" | "deaf_on" | "deaf_off";

/**
 * Whether a room participant may publish audio and video, or only receive it.
 */
export type VoiceRole = "publisher" | "viewer";

/**
 * The state of one voice room: who is in it, their kind of channel, and every participant's
 * mic, video, speaking, deaf, screen and hand state and role.
 */
export type VoiceRoom = { 
/**
 * The channel this room's signalling is scoped to.
 */
channel: string, 
/**
 * Whether every member publishes, or only the streamer and whoever they promote.
 */
kind: VoiceRoomKind, 
/**
 * Every known participant, keyed by their folded nick.
 */
participants: { [key in CaseFolded]?: VoiceParticipant }, 
/**
 * The TURN credentials the SFU handed us on `joined`, if it has yet.
 */
turn: TurnCredentials | null, };

/**
 * Who may publish in a voice room, decided by the channel's sigil.
 */
export type VoiceRoomKind = "publish" | "stream";

/**
 * One `+obsidianirc/rtc` signalling frame.
 *
 * Every variant is one JSON object's `type`. The published
 * <https://github.com/obbyworld/extensions/blob/main/voice.md> documents only 9 of these, the
 * wire carries 19, and this enum follows the wire. Outbound intent and inbound notification are modelled as distinct shapes where the
 * wire actually distinguishes them (`mic`/`video`/`screen`/`hand`/`speaking`/`silent`/`deaf`
 * versus the `presence` they get rebroadcast as; `promote`/`demote` versus `role`), rather than
 * collapsed into one type as the published table's prose implies.
 */
export type VoiceSignal = { "type": "join", 
/**
 * The channel to join.
 */
channel: string, } | { "type": "leave", 
/**
 * The channel to leave.
 */
channel: string, } | { "type": "joined", 
/**
 * Every current member's nick.
 */
members: Array<string>, 
/**
 * The room's kind, present only for a `$` channel.
 */
mode: VoiceRoomKind | null, 
/**
 * The role granted to us specifically, present only for a `$` channel.
 */
role: VoiceRole | null, 
/**
 * Who currently publishes, for a `$` channel.
 */
streamers: Array<string> | null, 
/**
 * The TURN credentials for this call.
 */
turn: TurnCredentials | null, 
/**
 * Hints mapping media lines to the members they belong to.
 */
tracks: Array<VoiceTrackHint> | null, } | { "type": "offer", 
/**
 * The offer SDP, or one slice of it when `chunk` is set.
 */
sdp: string, 
/**
 * Track-attribution hints, carried only on chunk 0 or an unchunked offer.
 */
tracks: Array<VoiceTrackHint> | null, 
/**
 * Set when this frame is one of several chunks sharing an id.
 */
chunk: ChunkMeta | null, } | { "type": "answer", 
/**
 * The answer SDP, or one slice of it when `chunk` is set.
 */
sdp: string, 
/**
 * Set when this frame is one of several chunks sharing an id.
 */
chunk: ChunkMeta | null, } | { "type": "ice", 
/**
 * The candidate string.
 */
cand: string, 
/**
 * The media line it applies to.
 */
mid: string | null, 
/**
 * The media line's index, when `mid` is absent.
 */
mlineidx: number | null, } | { "type": "presence", 
/**
 * Who this is about.
 */
member: string, 
/**
 * What changed.
 */
state: VoicePresence, 
/**
 * Which toggle, when `state` is [`PresenceState::On`] or [`PresenceState::Off`].
 */
kind: VoiceToggle | null, 
/**
 * The role granted, when `state` is [`PresenceState::Joined`] in a `$` room.
 */
role: VoiceRole | null, } | { "type": "mic", 
/**
 * The new state.
 */
state: OnOff, } | { "type": "video", 
/**
 * The new state.
 */
state: OnOff, } | { "type": "screen", 
/**
 * The new state.
 */
state: OnOff, } | { "type": "hand", 
/**
 * The new state.
 */
state: OnOff, } | { "type": "deaf", 
/**
 * The new state.
 */
state: OnOff, } | { "type": "speaking" } | { "type": "silent" } | { "type": "react", 
/**
 * Who reacted, present only on the inbound broadcast.
 */
member: string | null, 
/**
 * The emoji.
 */
emoji: string, } | { "type": "promote", 
/**
 * The member to promote.
 */
target: string, } | { "type": "demote", 
/**
 * The member to demote.
 */
target: string, } | { "type": "role", 
/**
 * Whose role changed.
 */
member: string, 
/**
 * Their new role.
 */
role: VoiceRole, } | { "type": "error", 
/**
 * A human-readable reason, when the server gave one.
 */
error: string | null, };

/**
 * Which per-participant toggle a `presence` notification reports, for its toggle sub-shape.
 */
export type VoiceToggle = "mic" | "video" | "screen" | "hand";

/**
 * A hint from the SFU mapping one negotiated media line to the member it belongs to.
 *
 * The SFU sends mid-to-member hints so an inbound track can be attributed to the right member
 * when the SDP's own `msid` is missing or unreliable. This is the minimal shape that serves that
 * purpose; a real server may send more fields, which this simply ignores on decode.
 */
export type VoiceTrackHint = { 
/**
 * The SDP media line identifier this hint names.
 */
mid: string, 
/**
 * The member that media line belongs to.
 */
member: string, };

/**
 * Who we are watching, and whether each is online.
 */
export type WatchList = { watching: Array<CaseFolded>, online: Array<CaseFolded>, };
