"""Type stubs for the obby_client extension module."""

from typing import Any

class Client:
    def __init__(
        self,
        nick: str,
        *,
        username: str | None = None,
        realname: str | None = None,
        password: str | None = None,
        sasl: dict[str, Any] | str | None = None,
        retention: int | None = None,
        alt_nicks: list[str] | None = None,
    ) -> None: ...
    @classmethod
    def from_config(cls, config: dict[str, Any] | str) -> Client: ...
    def handle_connected(self) -> None: ...
    def handle_disconnected(self) -> None: ...
    def handle_bytes(self, data: bytes) -> None: ...
    def poll_transmit(self) -> bytes | None: ...
    # The wire shapes are the generated TypeScript definitions in bindings/obby-wasm/src/types.d.ts;
    # Python has no generated model types yet.
    def poll_events(self) -> list[dict[str, Any]]: ...
    def poll_timeout(self) -> int | None: ...
    def tick(self, monotonic_ms: int, unix_ms: int) -> None: ...
    # The wire shapes are the generated TypeScript definitions in bindings/obby-wasm/src/types.d.ts;
    # Python has no generated model types yet.
    @property
    def model(self) -> dict[str, Any]: ...
    def command(self, command: dict[str, Any] | str) -> None: ...
    def join(self, channel: str, key: str | None = None) -> None: ...
    def part(self, channel: str, reason: str | None = None) -> None: ...
    def send_message(self, target: str, text: str) -> None: ...
    def send_notice(self, target: str, text: str) -> None: ...
    def send_action(self, target: str, text: str) -> None: ...
    def set_nick(self, nick: str) -> None: ...
    def set_topic(self, channel: str, topic: str | None = None) -> None: ...
    def set_away(self, message: str | None = None) -> None: ...
    def set_typing(self, target: str, state: str) -> None: ...
    def add_reaction(self, target: str, msgid: str, emoji: str) -> None: ...
    def remove_reaction(self, target: str, msgid: str, emoji: str) -> None: ...
    def redact_message(
        self, target: str, msgid: str, reason: str | None = None
    ) -> None: ...
    def mark_read(self, target: str, at_ms: int) -> None: ...
    def fetch_history(
        self, target: str, before_msgid: str | None = None, limit: int = 50
    ) -> None: ...
    def set_metadata(self, key: str, value: str | None = None) -> None: ...
    def subscribe_metadata(self, keys: list[str]) -> None: ...
    def watch_nicks(self, nicks: list[str]) -> None: ...
    def unwatch_nicks(self, nicks: list[str]) -> None: ...
    def send_voice_signal(self, channel: str, signal: dict[str, Any] | str) -> None: ...
    def quit(self, reason: str | None = None) -> None: ...
    def send_raw_line(self, line: str) -> None: ...
