"""Type stubs for the obby_client extension module."""

from typing import Any

class Client:
    def __init__(
        self,
        nick: str,
        *,
        username: str | None = None,
        realname: str | None = None,
        password: str | None = None,
        sasl: dict[str, Any] | str | None = None,
        retention: int | None = None,
        alt_nicks: list[str] | None = None,
    ) -> None: ...
    @classmethod
    def from_config(cls, config: dict[str, Any] | str) -> Client: ...
    def handle_connected(self) -> None: ...
    def handle_disconnected(self) -> None: ...
    def handle_bytes(self, data: bytes) -> None: ...
    def poll_transmit(self) -> bytes | None: ...
    def poll_events(self) -> list[ObbyEvent]: ...
    def poll_timeout(self) -> int | None: ...
    def tick(self, monotonic_ms: int, unix_ms: int) -> None: ...
    def model(self) -> Model: ...
    def command(self, command: Command | str) -> None: ...
    def join(self, channel: str, key: str | None = None) -> None: ...
    def part(self, channel: str, reason: str | None = None) -> None: ...
    def send_message(self, target: str, text: str) -> None: ...
    def send_notice(self, target: str, text: str) -> None: ...
    def send_action(self, target: str, text: str) -> None: ...
    def set_nick(self, nick: str) -> None: ...
    def set_topic(self, channel: str, topic: str | None = None) -> None: ...
    def set_away(self, message: str | None = None) -> None: ...
    def set_typing(self, target: str, state: str) -> None: ...
    def add_reaction(self, target: str, msgid: str, emoji: str) -> None: ...
    def remove_reaction(self, target: str, msgid: str, emoji: str) -> None: ...
    def redact_message(
        self, target: str, msgid: str, reason: str | None = None
    ) -> None: ...
    def mark_read(self, target: str, at_ms: int) -> None: ...
    def fetch_history(
        self, target: str, before_msgid: str | None = None, limit: int = 50
    ) -> None: ...
    def set_metadata(self, key: str, value: str | None = None) -> None: ...
    def subscribe_metadata(self, keys: list[str]) -> None: ...
    def watch_nicks(self, nicks: list[str]) -> None: ...
    def unwatch_nicks(self, nicks: list[str]) -> None: ...
    def send_voice_signal(self, channel: str, signal: VoiceSignal | str) -> None: ...
    def quit(self, reason: str | None = None) -> None: ...
    def send_raw_line(self, line: str) -> None: ...

# --- generated model types: start ---
#
# Generated by scripts/generate-model-types.py from bindings/obby-wasm/src/types.d.ts.
# Do not edit by hand.

from typing import Literal, TypedDict, Union

class AllowedCommands(TypedDict):
    available: list[str]


class Bot(TypedDict):
    nick: str
    id: str | None
    from_config: bool
    commands: list[BotCommand]


class BotCommand(TypedDict):
    name: str
    description: str | None


class BotRegistry(TypedDict):
    known: dict[str, Bot]


class Capabilities(TypedDict):
    available: dict[str, str | None]
    acknowledged: dict[str, str | None]
    pending: list[str]


class Capability(TypedDict):
    name: str
    value: str | None


CaseFolded = str


class Channel(TypedDict):
    name: str
    topic: str | None
    topic_by: str | None
    modes: dict[str, str | None]
    members: dict[CaseFolded, Membership]
    log: MessageLog
    unread: int
    mentions: int
    metadata: dict[str, str]
    read_marker: str | None
    typing: list[CaseFolded]
    named_modes: dict[str, str | None]


class ChatMessage(TypedDict):
    key: MessageKey
    msgid: str | None
    sender: str
    kind: MessageKind
    text: str
    account: str | None
    historical: bool
    own: bool
    reply_to: str | None
    reactions: dict[str, list[str]]
    link_preview: LinkPreview | None
    redacted: bool


class ChunkMeta(TypedDict):
    id: str
    seq: int
    total: int


class CommandJoin(TypedDict):
    type: Literal["join"]
    channel: str
    key: str | None

class CommandPart(TypedDict):
    type: Literal["part"]
    channel: str
    reason: str | None

class CommandSendMessage(TypedDict):
    type: Literal["send_message"]
    target: str
    text: str

class CommandSendNotice(TypedDict):
    type: Literal["send_notice"]
    target: str
    text: str

class CommandSendAction(TypedDict):
    type: Literal["send_action"]
    target: str
    text: str

class CommandSetNick(TypedDict):
    type: Literal["set_nick"]
    nick: str

class CommandSetTopic(TypedDict):
    type: Literal["set_topic"]
    channel: str
    topic: str | None

class CommandSetAway(TypedDict):
    type: Literal["set_away"]
    message: str | None

class CommandSetTyping(TypedDict):
    type: Literal["set_typing"]
    target: str
    state: TypingState

class CommandAddReaction(TypedDict):
    type: Literal["add_reaction"]
    target: str
    msgid: str
    emoji: str

class CommandRemoveReaction(TypedDict):
    type: Literal["remove_reaction"]
    target: str
    msgid: str
    emoji: str

class CommandRedactMessage(TypedDict):
    type: Literal["redact_message"]
    target: str
    msgid: str
    reason: str | None

class CommandMarkRead(TypedDict):
    type: Literal["mark_read"]
    target: str
    at_ms: int

class CommandFetchHistory(TypedDict):
    type: Literal["fetch_history"]
    target: str
    before_msgid: str | None
    limit: int

class CommandSetMetadata(TypedDict):
    type: Literal["set_metadata"]
    key: str
    value: str | None

class CommandSubscribeMetadata(TypedDict):
    type: Literal["subscribe_metadata"]
    keys: list[str]

class CommandWatchNicks(TypedDict):
    type: Literal["watch_nicks"]
    nicks: list[str]

class CommandUnwatchNicks(TypedDict):
    type: Literal["unwatch_nicks"]
    nicks: list[str]

class CommandSendVoiceSignal(TypedDict):
    type: Literal["send_voice_signal"]
    channel: str
    signal: VoiceSignal

class CommandQuit(TypedDict):
    type: Literal["quit"]
    reason: str | None

class CommandSendRawLine(TypedDict):
    type: Literal["send_raw_line"]
    line: str

Command = Union[CommandJoin, CommandPart, CommandSendMessage, CommandSendNotice, CommandSendAction, CommandSetNick, CommandSetTopic, CommandSetAway, CommandSetTyping, CommandAddReaction, CommandRemoveReaction, CommandRedactMessage, CommandMarkRead, CommandFetchHistory, CommandSetMetadata, CommandSubscribeMetadata, CommandWatchNicks, CommandUnwatchNicks, CommandSendVoiceSignal, CommandQuit, CommandSendRawLine]


class _ConfigRequired(TypedDict):
    nick: str

class Config(_ConfigRequired, total=False):
    username: str
    realname: str
    password: str
    sasl: SaslCredentials
    retention: int
    alt_nicks: list[str]


ConnectionPhase = Literal["disconnected", "negotiating", "registering", "registered"]


class Conversation(TypedDict):
    nick: str
    log: MessageLog
    unread: int
    read_marker: str | None
    typing: list[CaseFolded]


class Invitation(TypedDict):
    share_id: str
    channel: str | None
    url: str
    created: str | None
    redeemed: int
    description: str | None


class LinkPreview(TypedDict):
    title: str
    snippet: str | None
    image: str | None


class LocalUser(TypedDict):
    nick: str
    account: str | None
    modes: str
    metadata: dict[str, str]
    away: str | None


class Membership(TypedDict):
    prefixes: str


class MessageKey(TypedDict):
    time_ms: int
    seq: int


class MessageKindPrivmsg(TypedDict):
    type: Literal["privmsg"]

class MessageKindNotice(TypedDict):
    type: Literal["notice"]

class MessageKindCtcp(TypedDict):
    type: Literal["ctcp"]
    command: str

class MessageKindTagmsg(TypedDict):
    type: Literal["tagmsg"]

class MessageKindJoin(TypedDict):
    type: Literal["join"]

class MessageKindPart(TypedDict):
    type: Literal["part"]

class MessageKindQuit(TypedDict):
    type: Literal["quit"]

class MessageKindKick(TypedDict):
    type: Literal["kick"]
    target: str

class MessageKindNick(TypedDict):
    type: Literal["nick"]
    new_nick: str

class MessageKindTopic(TypedDict):
    type: Literal["topic"]

class MessageKindMode(TypedDict):
    type: Literal["mode"]

MessageKind = Union[MessageKindPrivmsg, MessageKindNotice, MessageKindCtcp, MessageKindTagmsg, MessageKindJoin, MessageKindPart, MessageKindQuit, MessageKindKick, MessageKindNick, MessageKindTopic, MessageKindMode]


class MessageLog(TypedDict):
    messages: list[ChatMessage]
    by_msgid: dict[str, MessageKey]
    retention: int


class MessageSource(TypedDict):
    name: str
    user: str | None
    host: str | None


class MessageTag(TypedDict):
    key: str
    value: str | None


MessageTags = list[MessageTag]


class Model(TypedDict):
    me: LocalUser
    channels: dict[CaseFolded, Channel]
    conversations: dict[CaseFolded, Conversation]
    people: dict[CaseFolded, Person]
    retention: int
    next_seq: int


class ModelChangeMessageAdded(TypedDict):
    type: Literal["message_added"]
    target: str
    key: MessageKey

class ModelChangeChannelJoined(TypedDict):
    type: Literal["channel_joined"]
    channel: str

class ModelChangeChannelParted(TypedDict):
    type: Literal["channel_parted"]
    channel: str

class ModelChangeChannelMembersChanged(TypedDict):
    type: Literal["channel_members_changed"]
    channel: str

class ModelChangeChannelTopicChanged(TypedDict):
    type: Literal["channel_topic_changed"]
    channel: str

ModelChangeNickChanged = TypedDict("ModelChangeNickChanged", {"type": Literal["nick_changed"], "from": str, "to": str})

class ModelChangeChannelModesChanged(TypedDict):
    type: Literal["channel_modes_changed"]
    channel: str

class ModelChangeReadMarkerMoved(TypedDict):
    type: Literal["read_marker_moved"]
    target: str

class ModelChangeMessageReacted(TypedDict):
    type: Literal["message_reacted"]
    target: str
    msgid: str

class ModelChangeMessageRedacted(TypedDict):
    type: Literal["message_redacted"]
    target: str
    msgid: str

class ModelChangeMetadataChanged(TypedDict):
    type: Literal["metadata_changed"]
    target: str
    key: str

ModelChange = Union[ModelChangeMessageAdded, ModelChangeChannelJoined, ModelChangeChannelParted, ModelChangeChannelMembersChanged, ModelChangeChannelTopicChanged, ModelChangeNickChanged, ModelChangeChannelModesChanged, ModelChangeReadMarkerMoved, ModelChangeMessageReacted, ModelChangeMessageRedacted, ModelChangeMetadataChanged]


class ObbyEventCapabilitiesAcknowledged(TypedDict):
    type: Literal["capabilities_acknowledged"]
    names: list[str]

class ObbyEventRegistered(TypedDict):
    type: Literal["registered"]
    nick: str

class ObbyEventIsupportToken(TypedDict):
    type: Literal["isupport_token"]
    token: str
    value: str | None

class ObbyEventLoggedIn(TypedDict):
    type: Literal["logged_in"]
    account: str

class ObbyEventSaslFailed(TypedDict):
    type: Literal["sasl_failed"]
    reason: SaslFailure

class ObbyEventNickInUse(TypedDict):
    type: Literal["nick_in_use"]
    refused: str
    trying: str

class ObbyEventModelChanged(TypedDict):
    type: Literal["model_changed"]
    change: ModelChange

class ObbyEventLinkDead(TypedDict):
    type: Literal["link_dead"]

class ObbyEventReconnectAfter(TypedDict):
    type: Literal["reconnect_after"]
    after_ms: int

class ObbyEventReconnectAbandoned(TypedDict):
    type: Literal["reconnect_abandoned"]

class ObbyEventCommandTimedOut(TypedDict):
    type: Literal["command_timed_out"]
    command: str

class ObbyEventAllowedCommandsChanged(TypedDict):
    type: Literal["allowed_commands_changed"]

class ObbyEventVoice(TypedDict):
    type: Literal["voice"]
    channel: str
    signal: VoiceSignal

class ObbyEventTypingChanged(TypedDict):
    type: Literal["typing_changed"]
    target: str
    nick: str
    active: bool

class ObbyEventPresenceChanged(TypedDict):
    type: Literal["presence_changed"]
    nick: str
    online: bool

class ObbyEventServerReply(TypedDict):
    type: Literal["server_reply"]
    severity: Severity
    command: str
    code: str
    context: list[str]
    text: str

class ObbyEventRawLine(TypedDict):
    type: Literal["raw_line"]
    message: RawMessage

ObbyEvent = Union[ObbyEventCapabilitiesAcknowledged, ObbyEventRegistered, ObbyEventIsupportToken, ObbyEventLoggedIn, ObbyEventSaslFailed, ObbyEventNickInUse, ObbyEventModelChanged, ObbyEventLinkDead, ObbyEventReconnectAfter, ObbyEventReconnectAbandoned, ObbyEventCommandTimedOut, ObbyEventAllowedCommandsChanged, ObbyEventVoice, ObbyEventTypingChanged, ObbyEventPresenceChanged, ObbyEventServerReply, ObbyEventRawLine]


OnOff = Literal["on", "off"]


class Person(TypedDict):
    nick: str
    account: str | None
    away: str | None
    bot: bool
    username: str | None
    host: str | None
    realname: str | None
    operator: bool
    metadata: dict[str, str]


class RawMessage(TypedDict):
    tags: MessageTags
    source: MessageSource | None
    command: str
    params: list[str]


class SaslCredentialsPlain(TypedDict):
    mechanism: Literal["plain"]
    username: str
    password: str

class SaslCredentialsExternal(TypedDict):
    mechanism: Literal["external"]

class SaslCredentialsScram(TypedDict):
    mechanism: Literal["scram"]
    username: str
    password: str
    nonce: str

SaslCredentials = Union[SaslCredentialsPlain, SaslCredentialsExternal, SaslCredentialsScram]


SaslFailure = Literal["rejected", "too_long", "aborted", "already_authenticated", "no_shared_mechanism", "server_not_verified"]


Severity = Literal["fail", "warn", "note"]


class TurnCredentials(TypedDict):
    urls: list[str]
    username: str
    password: str


TypingState = Literal["active", "paused", "done"]


class VoiceParticipant(TypedDict):
    nick: str
    role: VoiceRole
    mic: OnOff
    video: OnOff
    speaking: OnOff
    deaf: OnOff
    screen: OnOff
    hand: OnOff


VoicePresence = Literal["joined", "left", "on", "off", "speaking", "silent", "deaf_on", "deaf_off"]


VoiceRole = Literal["publisher", "viewer"]


class VoiceRoom(TypedDict):
    channel: str
    kind: VoiceRoomKind
    participants: dict[CaseFolded, VoiceParticipant]
    turn: TurnCredentials | None


VoiceRoomKind = Literal["publish", "stream"]


class VoiceSignalJoin(TypedDict):
    type: Literal["join"]
    channel: str

class VoiceSignalLeave(TypedDict):
    type: Literal["leave"]
    channel: str

class VoiceSignalJoined(TypedDict):
    type: Literal["joined"]
    members: list[str]
    mode: VoiceRoomKind | None
    role: VoiceRole | None
    streamers: list[str] | None
    turn: TurnCredentials | None
    tracks: list[VoiceTrackHint] | None

class VoiceSignalOffer(TypedDict):
    type: Literal["offer"]
    sdp: str
    tracks: list[VoiceTrackHint] | None
    chunk: ChunkMeta | None

class VoiceSignalAnswer(TypedDict):
    type: Literal["answer"]
    sdp: str
    chunk: ChunkMeta | None

class VoiceSignalIce(TypedDict):
    type: Literal["ice"]
    cand: str
    mid: str | None
    mlineidx: int | None

class VoiceSignalPresence(TypedDict):
    type: Literal["presence"]
    member: str
    state: VoicePresence
    kind: VoiceToggle | None
    role: VoiceRole | None

class VoiceSignalMic(TypedDict):
    type: Literal["mic"]
    state: OnOff

class VoiceSignalVideo(TypedDict):
    type: Literal["video"]
    state: OnOff

class VoiceSignalScreen(TypedDict):
    type: Literal["screen"]
    state: OnOff

class VoiceSignalHand(TypedDict):
    type: Literal["hand"]
    state: OnOff

class VoiceSignalDeaf(TypedDict):
    type: Literal["deaf"]
    state: OnOff

class VoiceSignalSpeaking(TypedDict):
    type: Literal["speaking"]

class VoiceSignalSilent(TypedDict):
    type: Literal["silent"]

class VoiceSignalReact(TypedDict):
    type: Literal["react"]
    member: str | None
    emoji: str

class VoiceSignalPromote(TypedDict):
    type: Literal["promote"]
    target: str

class VoiceSignalDemote(TypedDict):
    type: Literal["demote"]
    target: str

class VoiceSignalRole(TypedDict):
    type: Literal["role"]
    member: str
    role: VoiceRole

class VoiceSignalError(TypedDict):
    type: Literal["error"]
    error: str | None

VoiceSignal = Union[VoiceSignalJoin, VoiceSignalLeave, VoiceSignalJoined, VoiceSignalOffer, VoiceSignalAnswer, VoiceSignalIce, VoiceSignalPresence, VoiceSignalMic, VoiceSignalVideo, VoiceSignalScreen, VoiceSignalHand, VoiceSignalDeaf, VoiceSignalSpeaking, VoiceSignalSilent, VoiceSignalReact, VoiceSignalPromote, VoiceSignalDemote, VoiceSignalRole, VoiceSignalError]


VoiceToggle = Literal["mic", "video", "screen", "hand"]


class VoiceTrackHint(TypedDict):
    mid: str
    member: str


class WatchList(TypedDict):
    watching: list[CaseFolded]
    online: list[CaseFolded]

# --- generated model types: end ---
