/* The C ABI for obby-client. Generated by cbindgen: do not edit by hand.
 *
 * Thread safety: a handle is not synchronised. Never use one handle from two threads at once, not
 * even for two calls that only read. Give each thread its own handle, or take your own lock. */

#ifndef OBBY_FFI_H
#define OBBY_FFI_H

/* Generated with cbindgen:0.29.4 */

/* Regenerate with: cbindgen --config bindings/obby-ffi/cbindgen.toml --crate obby-ffi --output bindings/obby-ffi/include/obby_ffi.h */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * One connection's engine state.
 *
 * Created by [`obby_client_new`] and destroyed by [`obby_client_free`]. The caller only ever holds
 * a pointer to one; every operation on it goes through a function in this crate.
 */
typedef struct obby_client_t obby_client_t;

/**
 * An owned byte buffer handed out by [`obby_client_poll_transmit`].
 *
 * Freed with [`obby_client_free_bytes`], the only legal way to release it. An empty buffer is
 * always the zeroed value: a null `ptr` and a zero `len`, which is safe to free as a no-op.
 */
typedef struct obby_bytes_t {
    /**
     * The first byte, or null when `len` is zero.
     */
    uint8_t *ptr;
    /**
     * How many bytes `ptr` points to.
     */
    size_t len;
} obby_bytes_t;

/**
 * Create a client from a JSON-encoded [`Config`].
 *
 * Returns null when `config_json` is null, is not valid UTF-8, or does not parse as a `Config`.
 *
 * # Safety
 * `config_json` must be null or point to a NUL-terminated, valid UTF-8 C string, valid for reads
 * for the duration of this call.
 */
struct obby_client_t *obby_client_new(const char *config_json);

/**
 * Destroy a client created by [`obby_client_new`].
 *
 * # Safety
 * `client` must be null or a pointer returned by [`obby_client_new`] that has not already been
 * freed. It must not be used again after this call.///
 *
 * The handle must not be in use on another thread while this call runs.
 */
void obby_client_free(struct obby_client_t *client);

/**
 * Tell the engine the transport is up. See [`obby_client::Client::connected`].
 *
 * # Safety
 * `client` must be null or a valid, non-freed pointer from [`obby_client_new`].///
 *
 * The handle must not be in use on another thread while this call runs.
 */
void obby_client_connected(struct obby_client_t *client);

/**
 * Tell the engine its transport died. See [`obby_client::Client::disconnected`].
 *
 * # Safety
 * `client` must be null or a valid, non-freed pointer from [`obby_client_new`].///
 *
 * The handle must not be in use on another thread while this call runs.
 */
void obby_client_disconnected(struct obby_client_t *client);

/**
 * Feed bytes read from the transport.
 *
 * A null `data` is only valid when `len` is zero; any other null-with-nonzero-length call is
 * treated as if nothing were fed, rather than read out of bounds.
 *
 * # Safety
 * `client` must be null or valid. When `len` is greater than zero, `data` must point to at least
 * `len` readable bytes, valid for the duration of this call.
 *
 * The handle must not be in use on another thread while this call runs.
 */
void obby_client_handle_bytes(struct obby_client_t *client, const uint8_t *data, size_t len);

/**
 * Drain one pending outbound buffer, or the empty [`ObbyBytes`] when there is none.
 *
 * # Safety
 * `client` must be null or a valid, non-freed pointer from [`obby_client_new`].///
 *
 * The handle must not be in use on another thread while this call runs.
 */
struct obby_bytes_t obby_client_poll_transmit(struct obby_client_t *client);

/**
 * Free a buffer returned by [`obby_client_poll_transmit`].
 *
 * The only legal way to release one. Freeing the zeroed value (null `ptr`, zero `len`) is a no-op.
 *
 * # Safety
 * `bytes` must be a value returned by [`obby_client_poll_transmit`] that has not already been
 * freed, or the zeroed value.///
 */
void obby_client_free_bytes(struct obby_bytes_t bytes);

/**
 * Drain every pending event as one JSON array, `"[]"` when there are none.
 *
 * Returns null only when `client` is null; a working client always produces valid JSON.
 *
 * # Safety
 * `client` must be null or a valid, non-freed pointer from [`obby_client_new`].///
 *
 * The handle must not be in use on another thread while this call runs.
 */
char *obby_client_poll_events(struct obby_client_t *client);

/**
 * Free a string returned by [`obby_client_poll_events`] or [`obby_client_model_json`].
 *
 * The only legal way to release one. Never pass the pointer returned by [`obby_client_version`]
 * here: that one is static and owned by the library, not by the caller.
 *
 * # Safety
 * `s` must be null, or a pointer returned by [`obby_client_poll_events`] or
 * [`obby_client_model_json`] that has not already been freed.///
 */
void obby_client_free_string(char *s);

/**
 * Advance the clock. See [`obby_client::Client::tick`].
 *
 * # Safety
 * `client` must be null or a valid, non-freed pointer from [`obby_client_new`].///
 *
 * The handle must not be in use on another thread while this call runs.
 */
void obby_client_tick(struct obby_client_t *client, uint64_t monotonic_ms, uint64_t unix_ms);

/**
 * When the engine next has something to do, if ever.
 *
 * Returns `true` and writes the deadline to `*out_ms` when one is pending; returns `false`
 * otherwise, writing zero to `*out_ms` when it is non-null so the caller never reads uninitialised
 * memory either way.
 *
 * # Safety
 * `client` must be null or valid. `out_ms` must be null or point to a writable `u64` valid for the
 * duration of this call.///
 *
 * The handle must not be in use on another thread while this call runs.
 */
bool obby_client_poll_timeout(struct obby_client_t *client, uint64_t *out_ms);

/**
 * Submit a command from a JSON-encoded [`Command`].
 *
 * Returns `true` when it parsed and was submitted, `false` when `client` or `command_json` is
 * null, `command_json` is not valid UTF-8, or it does not parse as a `Command`.
 *
 * # Safety
 * `client` must be null or valid. `command_json` must be null or point to a NUL-terminated, valid
 * UTF-8 C string, valid for reads for the duration of this call.
 *
 * The handle must not be in use on another thread while this call runs.
 */
bool obby_client_command(struct obby_client_t *client, const char *command_json);

/**
 * Read the whole model as JSON, for a host that wants the full state rather than the changes.
 *
 * Returns null only when `client` is null; a working client always produces valid JSON.
 *
 * # Safety
 * `client` must be null or a valid, non-freed pointer from [`obby_client_new`].///
 *
 * The handle must not be in use on another thread while this call runs.
 */
char *obby_client_model_json(struct obby_client_t *client);

/**
 * The crate version, as a static, NUL-terminated string.
 *
 * This pointer is owned by the library and lives for the process's lifetime: never pass it to
 * [`obby_client_free_string`].
 */
const char *obby_client_version(void);

#endif  /* OBBY_FFI_H */
